### ISSUE TITLE
Simple micro page for try keboola

### ISSUE THREAD

**Issue by ujovlado** [keboola/indigo-ui#101]
https://keboola.slack.com/archives/C5CLTL7MK/p1519038848000199

Toto je na Jacka, ziadal to Padak.

Ide o to, ze by sa malo upravila try.keboola.com, tak aby bolo jasne, ze je to na zakladanie projektov.

Formular by ostal, zmenil by sa len design.

cc @jancermak

**Comment by janmichek** [comment]
@ujovlado Budem toto nakonec resit, nebo ne?

**Comment by ujovlado** [comment]
No vcera som sa o tom bavil s @jancermak , hovoril, ze by nieco simple pripravil.

Ci to ideme riesit sa skor spytaj @padak

**Comment by janmichek** [comment]
Ok, diky za update, ke me se to nedostalo 😅

**Comment by ujovlado** [comment]
Tak je to tu napisane, Jack to ma v TODO, nahodou som sa ho to opytal, ci to robil/nerobil. Netlacim na to. O tom ci to treba/netreba musi fakt rozhodnut Padak. Asi ked to ziadal, tak to treba. ;)

**Comment by jancermak** [comment]
@ujovlado @janmichek @padak 

Ahoj udelal jsem to jednoduse — vychazim z prihlasovaci obrazovky do KBC. Dava mi to logickou navaznost.  Jako uzivatel mam pocit ze uz jsem vlastne v produktu.

Udelal jsem dekstop i responziv mobil.

![101 simple micro page for try keboola desktop](https://user-images.githubusercontent.com/1826442/38944124-5c75082a-4333-11e8-93ee-f2edab331678.png)
![101 simple micro page for try keboola desktop copy](https://user-images.githubusercontent.com/1826442/38944134-62eb11c2-4333-11e8-955e-5080e25eedb7.png)

Mobil
![101 simple micro page for try keboola mobile](https://user-images.githubusercontent.com/1826442/38944154-6c4e44e6-4333-11e8-9b44-81787a0e0e30.png)

![101 simple micro page for try keboola mobile copy](https://user-images.githubusercontent.com/1826442/38944163-724122ba-4333-11e8-9442-49b08fd4f22b.png)
