### ISSUE TITLE
Universal spacing classes

### ISSUE THREAD

**Issue by ujovlado** [keboola/indigo-ui#106]
In bootstrap v4, there are great spacing classes:
https://getbootstrap.com/docs/4.0/utilities/spacing/

I'll init something like that in indigo-ui.

**Comment by ujovlado** [comment]
@janmichek ak by si chcel, mozeme tam este nieco pridat, pripadne to urobit inak. Toto je len nejaky zaklad, aby si kazdy (ako napr. ja) nemusel vymyslat svoje classes, ked chce niecomu dat margin/padding.

**Comment by janmichek** [comment]
Jsem s tim v pohode, muze se to hodit. Vetsinou se snazim obejit bez techto helperu a vyresit to na urovni navrhu. Muze se z toho stat mor kdyz se to dostane pod ruku backendovym programatorum xD

**Comment by ujovlado** [comment]
Kukni sa ked tak sem, tu je prve miesto, kde som to pouzil:

https://github.com/keboola/kbc-ui/commit/3d04790dbcd9784ac120adb59f46dfd4585b5cbe

Ak je to takto zle, kludne to poriesme, nech sa to fixne este v zarodku. ;)

**Comment by janmichek** [comment]
Me se to bohuzel moc nelibi. Zaplatujes chyby layoutu. Chapu proc to delas, ale paddingy by nemeli byt reseny temahle classama. Html se pak stane stylesheetem a je to uz videt -> 'no-padding', 'mx-2'. Melo by to byt vyreseny na urovni navrhu. Jen ve vyjimecnym pripade, pokud se svadi boj o specificitu selectoru, nebo jinych neresitelnych pripadech. Je to takovej quickfix, ale globalne pujde spis o zhorseni. 
Spekulace co se stane ted xD nekdo si toho quickfixu vsimne zes to pouzil a prijde mu to jako legit duvod to zacit propagovat. Trochu mensi zlo - lepsi pro budouci sjednoceni mi prijde odpoalovat vertikalni whitespace pomoci `<br>`

**Comment by ujovlado** [comment]
Ok, preto ti pisem - skus to kludne navrhnut lepsie/opravit ma.

ad `no-padding`:

je to jedno z mala miest kde sa to pouziva, ide o to, ze v orchestraciach v detaile jobu je to bez tych paddingov a natlacene navrch. pride mi lepsie tam dat `no-padding` (je to samopopisne ako to ostylovat skrz `orchestration-job-detail-xyz` (ako to bolo doteraz)

ad `mx-2`:

pridava to horizontalny padding, prave na mieste, kde chybal. napr. v eventoch (orchestr. job detail) by som to na search bar mal dat tiez -> lebo tabulka je na full sirku no search uz potom vyzera zle.

ad `<br>`:

takto sa imho riesil padding v roku 2000 :) ... preco by som mal pridat markup kvoli vyrieseniu vertikalneho spacingu? to uz dam radsej inline style.

**Comment by ujovlado** [comment]
@janmichek rozmyslam, ze by som toto vyhodil, ked tie spacing classy nechceme pouzivat ... alebo to nechat prave na hotifxy ako bol ten detail eventu?

**Comment by janmichek** [comment]
Predelam lepe to co jsem dneska hotfixoval.
Potom bych tyhle spacing classy vyhodil, akorat to bude nekoho lakat k pouziti xD Jako ja jsem se dnes nechal nalakat.
Hotfixovat muzes vzdy inline styly.
Dam vedet az to bude ready k vyhozeni.
