### ISSUE TITLE
upgrade hlavicek vsech komponent

### ISSUE THREAD

**Issue by jancermak** [keboola/indigo-ui#110]

**Comment by janmichek** [comment]
Jenom zopakuju: navrhuju vyscreenovat vsechny hlavicky - nebo aspon najit vsechny krajni hodnoty, co to muze obsahovat, jak dlouhy to ma obsah, atd. Pro ex, wr, aplikace.

**Comment by jancermak** [comment]
@janmichek — ahoj tady jest nahozeno — https://invis.io/7SGKYOXHY6N#/287989309_110-hlavicky-Komponent

—vytvoril jsem pravidla podle ruzneho obsahu
—ukazuju to i na prikladech

**Comment by janmichek** [comment]
Dobra prace pane Jacek, takhle jsem si to predstavoval.
Technicka idea je (a tohle muze byt prvni vlastovka) aby jsme meli komponentu zdokumentovanouv Indigu a pouzitou v KBC i v dalsich appkach - v tomto pripade Developer Portal. 
Takze pokud k tomu mas nejaky feedbacky, zapracujem je. Potom bych to jeste rad zkonfrontoval = videl vedle sebe s hlavickou v Developer Portalu

**Comment by jancermak** [comment]
@janmichek ola feedback je tady http://take.ms/ROYbT (nazval bych to bombou) porovnani teto hlavicky s hlavickou v developer portalu — http://take.ms/MIPpJ  Je tam v zakladu shoda — vlevo ikona (v kbc doplneno o nazev aplikace a popisek) uprostred  - informace, vpravo - autor

**Comment by ujovlado** [comment]
Neviem, ci je to uplne dobry napad, lebo Jack to este predesignoval, takze v devportali sa to este kusok zmeni. Flexboxom to je, to je pravda, no nie som s tym uplne spoko - chcel som to prave doladit az to budem prerabat (pri jednej velkosti screenu sa to zobrazuje divne).

Tak ak je to nieco, co sa ide robit v blizkej dobe, bolo by lepsie to spravit po vlastnej linii.

Navyse, indigo-ui je este stavane aby slo v kbc-ui (React 14), a devportal uz je React 16. Nechcem teraz moc na tom palit cas. Samozrejme v buducnosti by to tak bolo super - aby aj devportal bral veci z indigo-ui.

**Comment by janmichek** [comment]
Zatim jsem to nahrubo prekopiroval z developer-portalu. Po technicky strance mi to pripada dobry.
Dale - pripodobnit vzhledu co nevrhnul Jack, upravit responsivitu

**Comment by janmichek** [comment]
@jancermak jeste k tomu vizualnimu navrhu mam dotaz - vidim tam ruzny hodnoty paddingu. Mame na to nejaky pravidlo? Domnivam se, ze lepsi je drzet paddingy v nejakym nasobku 4px, 5px

**Comment by jancermak** [comment]
@janmichek Spravne nahozene tema :-) 
Ano — posledni dobou jsem si zvykl na na padding vychazejici z 3px nasobku — 3,6,12,(18),24,(30),48,(60)... 
takze v tom mym navrhu staci — upravit
![kbc-ui-v1 2018-05-09 16-52-13](https://user-images.githubusercontent.com/1826442/39822024-df404702-53a9-11e8-9060-99098b2f234b.png)
 a je to ready. 

S timto nasobkem jiz pocitam v novym styleguidu. Tak ho muzeme zacit aplikovat rovnou.

**Comment by janmichek** [comment]
Pockam az v produkci bude nasazeny badges https://github.com/keboola/kbc-ui/issues/1464
 a potom budu pokracovat v tomto. Souvisi to spolu.

**Comment by janmichek** [comment]
@jancermak Tady by to chtelo rozkreslit i pro ostatni detailovy podstranky (tf, job, orchestrace)
