### ISSUE TITLE
Obrazek — keboola academy v priprave

### ISSUE THREAD

**Issue by jancermak** [keboola/indigo-ui#124]
jancermak namaloval bys nám nějaký PNG, který říká, že nový Keboola Academy je v přípravě? To bych pak hodil místo keboola.academy - DNS bych přesměroval někam - klidně na S3 - kde bude ten jeden obrázek. Co ty na to, martin? (edited)

**Comment by jancermak** [comment]
@padak @Halama  Micro prototyp zde — https://invis.io/7CGOEIYDPW3#/289165992_keboola_Academy_4
Je potreba nekam nasmerovat ukladani pripadnych emailu. Muzeme je pak pozvat na beta testovani.

@janmichek  — pridal jsem te do invisionu, v sekci inspect mode jsou pripraveny SVG (napis keboola academy,  hortensie keboola s trychtirem 1 a 2) pro jistotu davam i sem


[keboola-academy-svg.zip](https://github.com/keboola/indigo-ui/files/1876218/keboola-academy-svg.zip)

**Comment by Halama** [comment]
Za mě je to ok, jenom si nejsem jistej tím textem. Nemá to být spíš `We are preparing`?

@janmichek mohl by ses prosím postarat o nařezání? Já bych se potom postaral o nahození.

**Comment by janmichek** [comment]
Jo, nebo takhle - neni co rezat .] je to SVG  - vektorova grafika, tak to staci jenom spravne umistit.
Pracuje se s tim podobne jako tady. Pripadne dej vedet pokud by ses ztracel ve stylovani, postaram se o to

**Comment by Halama** [comment]
Myslim tim nahodit repo kde bude ta html stranka funkcni.

**Comment by janmichek** [comment]
No prob, nahodim repo 'keboola-academy' s tou html strankou.

**Comment by janmichek** [comment]
@Halama jeste to potrebuju trochu dostylovat, ale pokud to chces napojit, svuj ucel to zatim splni .]

https://github.com/keboola/keboola-academy

**Comment by Halama** [comment]
Super, díky. Takhle to zatím v pohodě stačí. Nahodím tomu CI a pak se to případně může ladit.

**Comment by janmichek** [comment]
Feer, tak pak dej vedet jakmile to bude ready

**Comment by Halama** [comment]
Tady to zavírám a pokračujme tady https://github.com/keboola/keboola-academy/issues
