### ISSUE TITLE
Improve Storybook layout

### ISSUE THREAD

**Issue by janmichek** [keboola/indigo-ui#126]
soucasny stav, nevypada to prilis dobre.
![untitled-1](https://user-images.githubusercontent.com/15363559/38361059-68599d20-38cc-11e8-823e-dd24e3d49e1e.jpg)

Navrhuju prekopirovat zmeny z V1 kde uz to bylo vyreseny
![image](https://user-images.githubusercontent.com/15363559/38361080-7afffbe0-38cc-11e8-8e03-5eabc45c3c52.png)

**Comment by ujovlado** [comment]
Este by to ale chcelo odlisit tu cast, kde sa renderuje komponenta pre ktory je ta story. Ked to je vsetko biele moc to rozlisene nie je. Niekde som videl, ze tam bali ako transparent backgorund - ako cielova vlajka.

**Comment by ujovlado** [comment]
Nieco ako: http://airbnb.io/react-dates

**Comment by ujovlado** [comment]
Ale netrvam na tom, ak to bude jasne ... tych sposobom je hodne: https://storybook.js.org/examples/

**Comment by janmichek** [comment]
dik za postrehy, neco s tim udelam

**Comment by janmichek** [comment]
![image](https://user-images.githubusercontent.com/15363559/38880490-27356e70-4266-11e8-876b-195e0bac3fcf.png)
