### ISSUE TITLE
add knobs

### ISSUE THREAD

**Issue by janmichek** [keboola/indigo-ui#13]
https://github.com/storybooks/storybook/tree/master/addons/knobs

**Comment by janmichek** [comment]
Tady bych potreboval pomoct s instalaci addonu.
Nedari se mi nainstalovat addon Knobs an SetOptions. 
Kvuli teto chybe:

gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.

@ujovlado nejaky napad?

**Comment by ujovlado** [comment]
@janmichek isiel som podla navodu, podarilo sa mi to na prvy raz.

To s tym pythonom bude chyba tvojho PC/instalacie nodu ... pogoogli si to, vyzera to na nenastavenu `PATH`
