### ISSUE TITLE
Input mapping custom period — ux upgrade

### ISSUE THREAD

**Issue by jancermak** [keboola/indigo-ui#133]
1)je potreba mit tak velky "input" kdyz tam napisu na zacetek 2 hours — http://take.ms/HAUpLM
2)jestli jsem pochopil dobre je potreba psat cely slovo hours, minutes etc. Jelikoz jsem lenoch tak by mi stacilo jenom, h,m, s

**Comment by janmichek** [comment]
@jancermak ten zkracenej zapis m, h, d ... funguje
ten input je docela dlouhej, ale sousedi to se stejne dlouhyma, tak bych se na to zatim vyprdnul.
Za me v klidku
