### ISSUE TITLE
alert-block is used on other places so some error messages are broken

### ISSUE THREAD

**Issue by ujovlado** [keboola/indigo-ui#138]
![screenshot_2018-04-20_18-53-23](https://user-images.githubusercontent.com/419849/39063730-4ac6cfd8-44cc-11e8-9e08-90278be25557.png)

Usages:
https://github.com/keboola/connection/search?utf8=%E2%9C%93&q=+%22alert-block%22&type=

Budu rozbite pravdepodobne len tie, co su v kombinacii s danger alebo warning

cc: @janmichek

**Comment by janmichek** [comment]
Lol, to je blba chyba, nevsiml jsem si ze classa se jmenuje stejne.
Hlavne .alert-block ani nic nedela, nema prirazeny zadny styl.

KOukam ze se to vyskytuje jeste tady, ale predpokladam, ze to je nejaky vygenerovany HTML z Connection? https://github.com/keboola/storage-api-console/search?utf8=%E2%9C%93&q=alert-block&type=

**Comment by ujovlado** [comment]
Ok, takze riesenim je len vyhodit tie classy z markupu?

**Comment by janmichek** [comment]
Presne tak, je na to pripraveny PR. Zadny styly pro .alert-block predtim  nikdy nebyly

**Comment by ujovlado** [comment]
Aha, tak potom to iste aj do tej storage-console co si linkoval :)

**Comment by janmichek** [comment]
Fixed

**Comment by janmichek** [comment]
@ujovlado muzes to mergnout, at to nestrasi v produkci

**Comment by ujovlado** [comment]
Obidve casti, kde to bolo rozbite su fixed, uz bezi deploy connection.
