### ISSUE TITLE
Keboola - com — feedback

### ISSUE THREAD

**Issue by jancermak** [keboola/indigo-ui#141]
Pavel chtel feedback na wireframe a grafiku novyho webu keboola.com
https://paper.dropbox.com/doc/Keboola_com-WGbDzF6sdJ3yvNtPQomT6?_tk=share_copylink

**Comment by janmichek** [comment]
@jancermak btw je jeste neco potreba udelat s touhle issue?

**Comment by jancermak** [comment]
@janmichek  — Nope tuto uz je done, zaviram to

**Comment by janmichek** [comment]
Dobra, ale jak nalozime s tim feedbackem? Kdyz to bude zavreny, tak uz si na to nikdo nevzpomene

**Comment by jancermak** [comment]
Muzem ho predat Pavlovi D. nebo hodit do basecampu co maji k tvorbe webu keboola.com, jinak bych to tu moc nedrzel.
