### ISSUE TITLE
Remove ul padding when there's no icon?

### ISSUE THREAD

**Issue by ujovlado** [keboola/indigo-ui#150]
![screenshot_2018-05-03_16-48-16](https://user-images.githubusercontent.com/419849/39584087-dee267ac-4ef1-11e8-9883-7dcac9d654e5.png)

@janmichek usla tam myslim este jedna vec. V alert bloku vzdy nemusi byt ikonka

**Comment by janmichek** [comment]
To mi asi uniklo, jak jsem delal v nekolika vetvich najednou. Opravim

**Comment by ujovlado** [comment]
Blbost, sorry.

**Comment by janmichek** [comment]
Ne tak docela, tvouj feedback byl opravnenej, dalo se to udelat lip https://github.com/keboola/indigo-ui/pull/153

**Comment by ujovlado** [comment]
No ja som to zavrel, lebo tu chybu som nevedel nasimulovat a pravdepodobne to bola moja chyba, ked som nemal aktualne indigo v kbc-ui.

**Comment by janmichek** [comment]
nn, ja vim o co jde. Muzes to mergnout prosim https://github.com/keboola/indigo-ui/pull/153
