### ISSUE TITLE
uprava diagramu

### ISSUE THREAD

**Issue by janmichek** [keboola/indigo-ui#154]
- potrebujem upravit existujuci diagram k ETL ktory je v Guide modu aby tam bolo jasnejšie / explicitne znázornené Extract / Transform / Load fáza
- potrebujem diagram ktorý znázorňuje relationship medzi Maintainerom, Organizáciou a Projektami, a zdieľanie bucketov medzi danými projektami v rámci organizácie
- potrebujem diagram zobrazujúci vzťah medzi Storage / Bucketmi / Tabulkami tak aby to bralo v potaz in. a out. fázu

**Comment by jancermak** [comment]
Poznamka pro me: domluvit s TFkem  obsahlejsi zadani.

**Comment by jancermak** [comment]
**Pro TFka:**
—zeleně jsem oznacil mnou preferovane verze
—u trasnfomracniho sadnboxu si nejsem jist jestli jsem to nakreslil OK

![154 uprava diagramu tfko 1 2x](https://user-images.githubusercontent.com/1826442/40438508-8a2174de-5eb8-11e8-9149-14a8f2c52a81.png)
![154 uprava diagramu tfko 3 2x](https://user-images.githubusercontent.com/1826442/40438509-8a411348-5eb8-11e8-82c2-7fd4af4efb03.png)
![154 uprava diagramu tfko 2 2x](https://user-images.githubusercontent.com/1826442/40438510-8a656036-5eb8-11e8-8fc1-819eaa1ffadd.png)
![154 uprava diagramu tfko 5 2x](https://user-images.githubusercontent.com/1826442/40438511-8a84b88c-5eb8-11e8-8055-ef396ee592c1.png)
![154 uprava diagramu tfko 4 2x](https://user-images.githubusercontent.com/1826442/40438512-8aa3e57c-5eb8-11e8-9a08-ff32d8d61e37.png)

**Comment by jancermak** [comment]
—upraveno final ZIP zde — (PNG + SVG)
—invission — https://invis.io/3AJC3P6C7GQ#/298900053_-154_-_Uprava_Diagramu_TFko_-_1

![etl-in-kbc 2x](https://user-images.githubusercontent.com/1826442/40717759-db17f46c-640d-11e8-9421-eacd8365abf7.png)
![relationship 2x](https://user-images.githubusercontent.com/1826442/40717760-db3d7aca-640d-11e8-844c-564ab6d957d0.png)
![sandbox 2x](https://user-images.githubusercontent.com/1826442/40717761-db5db1aa-640d-11e8-92dc-0fccd10dabde.png)
![storage-bucket-tables 2x](https://user-images.githubusercontent.com/1826442/40717762-db828b2e-640d-11e8-827a-03943bb48b7a.png)
![transformation sandbox 2x](https://user-images.githubusercontent.com/1826442/40717763-dba10fc2-640d-11e8-968f-870744b3fe7c.png)
[KBC-diagramy.zip](https://github.com/keboola/indigo-ui/files/2053688/KBC-diagramy.zip)

**Comment by janmichek** [comment]
Bomby, mam radost. Ted uz ETL pochopi i moje babicka xD 
Osobne bych to drzel vizualne minimalistictejsi - vyjit s min vizualnima prvkama - netristit pozornost na ruzny vizualni styly. Ale svuj ucel to splni, takze gut!
