### ISSUE TITLE
Contrast between h2 and label on win/nix

### ISSUE THREAD

**Issue by pivnicek** [keboola/indigo-ui#155]
The s3 extractor and db extractors are using `h2` to mark form sections.  This looks good on the mac because there is a contrast between the styles, but on win/nix browsers the `h2` does not have much difference to the `label`.

**Comment by ujovlado** [comment]
This will be probably solved with new font which have both 300 and 400 weights.

**Comment by ujovlado** [comment]
Anyway, I wonder if we can tune `font-family` to fallback to some system font which have also both sizes? E.g. to `system-ui`?

**Comment by ujovlado** [comment]
For example, in my case, `system-ui` means I'll have nice Ubuntu font in UI. :)

**Comment by janmichek** [comment]
Possible fix https://github.com/keboola/indigo-ui/issues/27

**Comment by janmichek** [comment]
Fixed
![image](https://user-images.githubusercontent.com/15363559/43071078-e89f458e-8e71-11e8-8bbd-2e7342b77c7f.png)
