### ISSUE TITLE
4K backgrounds

### ISSUE THREAD

**Issue by janmichek** [keboola/indigo-ui#167]
Na 4k rozliseni ma login stranka cropnuty background. Optimalizovat na 4k rozliseni. 
Nehodnotim ted ze browser pres 4k je prasarna xD

screenshot ani ne z 4k rozliseni
![image](https://user-images.githubusercontent.com/15363559/40175304-f768baa6-59d7-11e8-8010-8ec5ab6b0a59.png)

**Comment by jancermak** [comment]
@janmichek 
Posilam 8 kousku (i varianta se zakreslenim login okna) — 3 kousky jsou z offsitu :-)

Zabaleny v zipu ke stazeni zde
[4K-login-images.zip](https://github.com/keboola/indigo-ui/files/2075630/4K-login-images.zip)

— nahledy se zakreslenym loginem (4K)
![bg1-with-login](https://user-images.githubusercontent.com/1826442/41031615-5ebee618-6981-11e8-9727-d42bf314c679.jpg)
![bg2-with-login](https://user-images.githubusercontent.com/1826442/41031616-5edc971c-6981-11e8-9154-a36e0b3f7e58.jpg)
![bg3-with-login](https://user-images.githubusercontent.com/1826442/41031617-5f0157a0-6981-11e8-8891-6d83063e5a74.jpg)
![bg4-with-login](https://user-images.githubusercontent.com/1826442/41031618-5f1f7c1c-6981-11e8-9319-2e6f6f04c1f8.jpg)
![bg5-with-login](https://user-images.githubusercontent.com/1826442/41031619-5f3de1d4-6981-11e8-995a-367de4f612c3.jpg)
![bg6-with-login](https://user-images.githubusercontent.com/1826442/41031620-5f65b498-6981-11e8-876a-240832a28dd3.jpg)
![bg7-with-login](https://user-images.githubusercontent.com/1826442/41031621-5f8c4b9e-6981-11e8-8175-b88250ee1adb.jpg)
![bg8-with-login](https://user-images.githubusercontent.com/1826442/41031623-5fa849b6-6981-11e8-93bb-487f0f595ad8.jpg)

**Comment by janmichek** [comment]
Fotky v topu - rikal jsem si ze nektery offsity neznam xD

**Comment by Halama** [comment]
odkud je ten zbytek? Meli bysme je mit koupeny.

**Comment by janmichek** [comment]
Jack schvalne vybiral fotky s CC0 licenci, aby to bylo pouzitelny. Licencne je to poreseny

**Comment by janmichek** [comment]
Hele co jsem jeste nasel
1) chovani pri scrollovani 
2) bg se vyskytuje i na vyberu projektu hned po loginu

![hele](https://user-images.githubusercontent.com/15363559/41346705-b3271262-6f07-11e8-906c-0642476f768e.gif)

**Comment by janmichek** [comment]
Nerikam, ze to musi bejt stejne, ale jenom abys vedel

**Comment by jancermak** [comment]
@janmichek —ty obrazky jsou hodne vysoky, ale rekneme extremni varianta monitor 4K a dlouhej seznam —> jde mit fixnuty pozadi? A scroluje mi pres to jen ten bilej modal?

@Halama — obrazky jsou z www.unsplash.com — tady je info k licenci — https://unsplash.com/license

**Comment by janmichek** [comment]
Urcite je moznost ten background mit zafixovany. Ani mi to neprijde kdovijak uhledny, jak to ted scrolluje. Kdyby tam byl parallax, tak by to vypadalo lip, ale to uz je zas overkill.

**Comment by jancermak** [comment]
@janmichek — ok zafixovany pozadi.

**Comment by janmichek** [comment]
Fajn, u tohoto nic nebrani nasazeni. Mel jsi s tim nejakou ideu, kdy zobrazovat jaky background, nebo ciste random? @jancermak 

+ implementacni detail pro me:
Vyrenderovat obrazky v ruznych rozlisenich a v cssku je servirovat podle sirky displaye at se na malym rozliseni nestahuje 4k obrazek. Standartni responzivni breakpointy.

**Comment by jancermak** [comment]
@janmichek — puvodni myslenka je čirý random.

**Comment by jancermak** [comment]
notička od padaka: pavel má super připomínku: “bylo by hezký tam mít napsaný, odkud ta fotka je a kdy vznikla + třeba link na mapu, aby to mělo ‘personal touch’“. Co vy na to?

**Comment by janmichek** [comment]
Muze byt, nijak na tom nelpim .] Nektery fotky jsou z offsitu - tam je to jasny. Mame mezi nima i nejaky stock photos, tak tam jak?

**Comment by ondrejhlavacek** [comment]
Nepoužít :-)

**Comment by jancermak** [comment]
Domluveno s Janem po telefonu — budou jenom nase fotky z offsitu, vyberu a pripravim vetsi sadu. Ke kazde fotce navrhnu popisek + link na google mapu.

**Comment by jancermak** [comment]
@janmichek 
—
U kazdy fotky je link na fotku v google photos, odkud lze vzit informace o casu a poloze pokud jsou
—  
![image](https://user-images.githubusercontent.com/1826442/41981753-f5f6e14e-7a29-11e8-98c8-465dad22b12e.png)

číslo fotky | link na fotku 
------------ | -------------
1 | https://photos.google.com/share/AF1QipP1YSL8_Nz-KB9ow8B7HOEJmuI26d6krvRhM-L1QlZ8j24wUqmKcZv-BnVOnEur3A/photo/AF1QipOnp7hTrhV_kEQkHZFsRr47bBZYn2UXwyX-2zGX?key=SDktUjg1eWdHSTMyRENDTWZfdWJoRzU5VTlJVXVn&hl=cs
2 | https://photos.google.com/share/AF1QipMLS6XoSLJwunCA_UYesvyYMj-BEaSInymx9il8Ipz-dyQfPKV3RFfb_2uawnYZIg/photo/AF1QipNtbT-ntEZPt0mooPpaCuwMPhtoM039KzLlPubk?key=STJFMVVhcDdwT3YwNktJZDc4R09GY2w0YlhUck1B&hl=cs
3 | https://photos.google.com/share/AF1QipP1YSL8_Nz-KB9ow8B7HOEJmuI26d6krvRhM-L1QlZ8j24wUqmKcZv-BnVOnEur3A/photo/AF1QipPE64RqvcN5Jf1Ks7MWD4ilhYR9zRzY8kE4GzZu?key=SDktUjg1eWdHSTMyRENDTWZfdWJoRzU5VTlJVXVn&hl=cs 
4 | https://photos.google.com/share/AF1QipO898OmTEi5deSwBQ4xq2CG8y5Z9YxgsmMx9_lU8Yj0l_l2c8BNdMvIVG9lqMObwg/photo/AF1QipNZhAB_f21cp_m2Qeu96EZW_DIy3IaMtjJPBSPf?key=M2VFSVVhRWNWMkwwQ0Y2OFFKdEwzQ1hBNVQ5djlB&hl=cs
5 | https://photos.google.com/share/AF1QipP1YSL8_Nz-KB9ow8B7HOEJmuI26d6krvRhM-L1QlZ8j24wUqmKcZv-BnVOnEur3A/photo/AF1QipOa8WLCXcsdPFmV-iEi2CflXjnJ8hr6VkU0lvlt?key=SDktUjg1eWdHSTMyRENDTWZfdWJoRzU5VTlJVXVn&hl=cs  prijezd do Mash Gargano u fotky neni GPS
6 | https://photos.google.com/share/AF1QipP1YSL8_Nz-KB9ow8B7HOEJmuI26d6krvRhM-L1QlZ8j24wUqmKcZv-BnVOnEur3A/photo/AF1QipM4Ds_SG0yfpXWfPu21e56ZhNMi1ZRcr-QmwG91?key=SDktUjg1eWdHSTMyRENDTWZfdWJoRzU5VTlJVXVn&hl=cs 
7 | https://photos.google.com/share/AF1QipMLS6XoSLJwunCA_UYesvyYMj-BEaSInymx9il8Ipz-dyQfPKV3RFfb_2uawnYZIg/photo/AF1QipO8BTxTw3WIzFoIga8AWYhULz0HrTAlHkUgY77k?key=STJFMVVhcDdwT3YwNktJZDc4R09GY2w0YlhUck1B&hl=cs 
8 | https://photos.google.com/share/AF1QipP1YSL8_Nz-KB9ow8B7HOEJmuI26d6krvRhM-L1QlZ8j24wUqmKcZv-BnVOnEur3A/photo/AF1QipMhBXvLOECIVTcR8NDKYdbKn7PkNcOFbvonuF-g?key=SDktUjg1eWdHSTMyRENDTWZfdWJoRzU5VTlJVXVn&hl=cs — Mash Gargano, zemepisna sirka: 41,9053, zemepisna delka: 15,5116

**Fotky komplet v ZIPu:**
[4K-bg-fotky.zip](https://github.com/keboola/indigo-ui/files/2142139/4K-bg-fotky.zip)

**JPGs:**
![bg1](https://user-images.githubusercontent.com/1826442/41987645-0d1ce606-7a3a-11e8-8bdb-b17be9f9516b.jpg)
![bg2](https://user-images.githubusercontent.com/1826442/41987646-0d3d4108-7a3a-11e8-8ac7-779041b5c0f3.jpg)
![bg3](https://user-images.githubusercontent.com/1826442/41987647-0d5cb2f4-7a3a-11e8-989a-3c72901eb2ea.jpg)
![bg4](https://user-images.githubusercontent.com/1826442/41987648-0d7aaea8-7a3a-11e8-9149-438e16b4b8a7.jpg)
![bg5](https://user-images.githubusercontent.com/1826442/41987649-0da188c0-7a3a-11e8-8ef6-6abab11ce1bc.jpg)
![bg6](https://user-images.githubusercontent.com/1826442/41987651-0dc1d1c0-7a3a-11e8-92f6-f18a64043461.jpg)
![bg7](https://user-images.githubusercontent.com/1826442/41987653-0de6338a-7a3a-11e8-9a05-97b5984ee3f9.jpg)
![bg8](https://user-images.githubusercontent.com/1826442/41987632-03a7b970-7a3a-11e8-9f65-42a2b0b4319a.jpg)

**Comment by janmichek** [comment]
Bomby, dik za pripravu.
Jeste mi tu chybi vizualni navrh ty informace.
Predpokladam ze vpravo / vlevo dole na obrazovce fixnu nejakej box s nazvem lokace?
Nebo jaka byla idea?

**Comment by jancermak** [comment]
Navrh umisteni popisku k fotce.

![167 4k login background](https://user-images.githubusercontent.com/1826442/41989399-75c41198-7a3f-11e8-94b9-b6dc94ce3fc6.png)

**Comment by padak** [comment]
Hele, vypadá to super! Až to spustíme, budou chtít ostatní přispívat svejma fotkama - tak pak by to chtělo nějakej "proces" kdo/co/kam může poslat k našemu review. V Kanadě teď proběhl (bohužel v tichosti) třeba první sraz klientů... tak občas přijdou akce, co nejsou offsite, který by se na to mohli kvalifikovat...

**Comment by janmichek** [comment]
Mam to pripraveny, jenom to potrebuju zchecknv Connection, az se mi to povede rozchodit, delal jsem to tam zatim naslepo. Pracoval jsem na lokalnim html.
Prikladam screencast, kde refreshuju a zkousim velikosti okna browseru

Source:
[bgs html.zip](https://github.com/keboola/indigo-ui/files/2146033/bgs.html.zip)

Screencast:
https://mega.nz/#!gAthHI6Y!ZROnJ2-ir-5Jp1KdgXRW69e6Oj_DLEYH7Ak34GSd3ew

**Comment by janmichek** [comment]
@ujovlado tady bych potom potreboval poradit, jak mam deployovat styly do produkce na indigo.keboola.com (ne nutne do novy verze package). Domnivam se ze predtim se pushem do masteru zbuildilo na prod verzi, a nebylo nutny releasovat novou verzi package, ted mi prijde ze to funguje jinak. Delam to podle navodu.

Chtel jsem tady https://indigo.keboola.com/?selectedKind=Splash&selectedStory=Splash%20Screeen&full=0&down=1&left=1&panelRight=0&downPanel=storybook%2Factions%2Factions-panel pripravit Martinovi demo tech backgroundu, aby to mohl zaimplementovat do Connection https://github.com/keboola/connection/pull/1409

**Comment by Halama** [comment]
Bylo by dobrý to nahodit i sem https://try.keboola.com/ cc @ujovlado

**Comment by ujovlado** [comment]
Nahodene aj na try.keboola.com https://github.com/keboola/project-creator-app/pull/16
