### ISSUE TITLE
Icon sizing

### ISSUE THREAD

**Issue by janmichek** [keboola/indigo-ui#178]
Najit optimalni zpusob sizovani ikon ze setu ikon.
Udelat research, naimplementovat v kbc, pote zdokumentovat.

**Comment by ujovlado** [comment]
Stale sa mozeme na to vykaslat a pouzit hotove ikonky. Font Awesome uz je davno vo verzii 4, ponukaju aj svg, nemyslim si, ze by sme tym utrpeli.

**Comment by janmichek** [comment]
@ujovlado  Zkusil jsem se na to podivat
Projel jsem par icon setu a podival jsem se jak se to pouziva, co maji spolecny.
tohle mi pijde pouzitelny za malo kodu.
https://github.com/keboola/indigo-ui/pull/264

**Comment by janmichek** [comment]
Pripadny cisla velikosti ikon bych potom odladil pri implementaci, dle konkretniho pouziti v kbc - s urictou rezervou.
