### ISSUE TITLE
Horizontal scrollbar

### ISSUE THREAD

**Issue by pivnicek** [keboola/indigo-ui#179]
In some places a horizontal scrollbar is appearing for some reason.

changing `kbc-main-content` to `overflow:hidden` gets rid of it, but that could maybe mess up other things.

I've seen the scrollbar on db extractors query detail page and db-writers configuration table listing page.  

Original issue: https://github.com/keboola/kbc-ui/issues/1663

**Comment by janmichek** [comment]
This is a case of improper use of bootstrap
Every child of '.row' should be followed by child '.col-*'.
So structure like '.col-* > .col-* > .col-*' or '.row > .row > .row' is causing this extra space problem.
Also '.form-group' is acting as a '.row'.

'<p class="col-xs-8" ...' seems to be experimental, would not be messing with this.

If possible fix it.
