### ISSUE TITLE
Grafický audit loaderů

### ISSUE THREAD

**Issue by janmichek** [keboola/indigo-ui#186]
vyscreenovat z KBC vsechny koncepty nacitani a udelat sjednoceny navrh

**Comment by janmichek** [comment]
Vyscreenoval jsem vsechny signalizace nacitani / prubehu napric aplikaci. Je mozny, ze jsem neco prehlidl, pomozte mi to pripadne doplnit.

![loaders](https://user-images.githubusercontent.com/15363559/41722452-e98bdc54-7568-11e8-8ed2-ea6f677f8c31.png)

**Comment by Halama** [comment]
Všude by mělo být použito https://github.com/keboola/indigo-ui/blob/master/src/indigo/components/Loader.jsx

Jediný který se liší je ten pro ty limity a to je tím že to je generováno Keen a Google graphs SDK kde to nemáme tolik pod kontrolou.

**Comment by janmichek** [comment]
jeste jeden 
![dalsi-loader](https://user-images.githubusercontent.com/15363559/41923328-765e1384-7967-11e8-8983-e33990269217.png)

**Comment by janmichek** [comment]
dalsi nalez
![image](https://user-images.githubusercontent.com/15363559/41984904-22bf2f8a-7a32-11e8-86fb-30d5e3c63876.png)

**Comment by janmichek** [comment]
![image](https://user-images.githubusercontent.com/15363559/42630330-a1bedb78-85d6-11e8-8b91-6ddef63e0de3.png)
