### ISSUE TITLE
Draghandle icon

### ISSUE THREAD

**Issue by janmichek** [keboola/indigo-ui#191]
Souhlas s Tomasovym navrhem.
https://keboola.slack.com/archives/C0LM9SK6K/p1530110505000322
@jancermak prosim dodej nam vektory

**Comment by jancermak** [comment]
[drag-icon.svg.zip](https://github.com/keboola/indigo-ui/files/2184551/drag-icon.svg.zip)

**Comment by janmichek** [comment]
Zaimplementuju, diky

**Comment by janmichek** [comment]
Ikona pripravena v indigu, jakmile projde tento PR
https://github.com/keboola/indigo-ui/pull/202

**Comment by janmichek** [comment]
Potom lze nahradit v Config rows
