### ISSUE TITLE
unify description style

### ISSUE THREAD

**Issue by janmichek** [keboola/indigo-ui#193]
![image](https://user-images.githubusercontent.com/15363559/42449151-ed388bca-837f-11e8-9b0a-b2c42c42b0c5.png)

vs. 

![image](https://user-images.githubusercontent.com/15363559/42449198-0fbaa12e-8380-11e8-8051-fd67f3ba179a.png)

bude souviset s https://github.com/keboola/indigo-ui/issues/189

**Comment by ujovlado** [comment]
Toto sme uz parcialne myslim vyriesili a nikde nemame descriptions upper case alebo tak.
