### ISSUE TITLE
Tune font-family settings

### ISSUE THREAD

**Issue by ujovlado** [keboola/indigo-ui#195]
Chcelo by to upratat, nech sa to nastavuje na jednom mieste. Zda sa mi, ze je v tom trosku bordel.

Related to: https://github.com/keboola/indigo-ui/pull/194

**Comment by ujovlado** [comment]
Tiez mozno checknut ako je to s pouzitim tychto variables:

```less
@font-family-sans-serif: "Whitney SSm A", "Whitney SSm B", sans-serif;
@font-family-base: @font-family-sans-serif;
```

**Comment by janmichek** [comment]
OK, poresim
