### ISSUE TITLE
Set Roboto font also in Storybook

### ISSUE THREAD

**Issue by ujovlado** [keboola/indigo-ui#196]

**Comment by janmichek** [comment]
Ja jsme pro drzet storybook co nejvic plain stylovany. Idealne cisty bootstrap. Nebo proc chces, aby komponenty meli defaultne font whitney? V pouzity aplikaci pak muze byt uplne jiny font, takze bych nechal Arial (defaultni font)

Nebo je rec o nastaveni fontu whitney jen pro samotny Storybook - s vyjimkou canvasu, kde se renderuji komponenty?

**Comment by ujovlado** [comment]
Chcel som to len preto aby sa dalo pozriet ako tie komponenty budu vyzerat, no potom sme ho tam stejne museli dat kvoli server render strankam connection.

T.j. ten font uz tam nastaveny je (https://github.com/keboola/indigo-ui/search?q=Whitney&unscoped_q=Whitney), momentalne len chyba loadnutie z cloud.typography. Navyse, Arial asi nema tolko rezov.
