### ISSUE TITLE
User menu dropdown

### ISSUE THREAD

**Issue by ujovlado** [keboola/indigo-ui#20]
_From @Halama on May 2, 2017 8:55_

![image](https://cloud.githubusercontent.com/assets/903531/25611031/d64822f4-2f25-11e7-9e2f-ae93e6f287af.png)

_Copied from original issue: keboola/kbc-bootstrap#44_

**Comment by janmichek** [comment]
Videl jsem to v rozbitim i pozdeji opravenym stavu. Ted nemuzu najit ten commit, ale tekhle rozpadle to uz nevypada.

**Comment by ujovlado** [comment]
@janmichek ak to mas fixnute v mastri, tak ok ... ale nechal by som to tu otvrene, az dovtedy kym to nebude fixnute v produkcii.

![screenshot_2017-09-04_15-18-01](https://user-images.githubusercontent.com/419849/30028200-6ac4089c-9184-11e7-8079-d6dbd14e1516.png)

**Comment by ujovlado** [comment]
Bude s tym este trosku jebacka a bude to treba zjednotit, lebo sa tam pouziva rozny markup (mozno az 3 verzie) ... viem o tom, lebo som to riesil pri upgrade na react 14 ;)

**Comment by janmichek** [comment]
Uz vidim kde je chyba, moje blbost, sorry.

**Comment by ujovlado** [comment]
Tu som to riesil: https://github.com/keboola/kbc-bootstrap/commit/6ed6f5c27b5bfbd2b8239c00c55831fd4d42c18a ... a potom este fix tu:
https://github.com/keboola/kbc-bootstrap/commit/e9d87d9f24b4ebbdd6ffdc0b29073f98738d6861

Islo o to, ze som to nechcel rozbit, tak som musel spravit aby to podporovalo rozny markup ( a nechcel som releasovat kvoli tomu connection)

Rozmyslam ale, ze az taky problem to mozno nebude, staci asi ak sa fakt vsade pouzije rovnaky markup. Pouziva sa to asi na 3 miestach, a niekde je este "server render", ktory sa po loade kbc-ui nahradzuje. To ale postupne poriesime :)

**Comment by janmichek** [comment]
Dobry, koukam ze ten markup neni uplne stastny...
Mam to teda resit nebo ne? Pripadne o jakych vyskytech dropdownu vis?

**Comment by ujovlado** [comment]
Asi nie je uplne vhodne rozrabat dalsiu vec (obavam sa, ze by sa to stejne muselo fixnut v indigo-ui `kbc-bootstrap` branch.

Ak to vydrzalo doteraz, este to myslim chvilku pocka. Urcite to ale bude treba fixnut. :)

Co sa pouzitia tyka, tak ak si odmyslis `kbc-bootstrap` a CSSka, tak by to mohol byt tento search
https://github.com/search?q=org%3Akeboola+%22kbc-user%22&type=Code

**Comment by janmichek** [comment]
ok, no probs

**Comment by janmichek** [comment]
Napadlo me v Indigu pouzivat priznak napr: 👌 aby developeri vedeli, co je k pouziti a co jeste ne

**Comment by Halama** [comment]
Připomínám se:) 
![image](https://user-images.githubusercontent.com/903531/43773280-882e0e30-9a45-11e8-875f-410d67011c7f.png)

**Comment by Halama** [comment]
chvilka už uplynula viz. https://github.com/keboola/indigo-ui/issues/20#issuecomment-328532357

**Comment by ujovlado** [comment]
tak uz viem kolko je chvilka :) rok :tada:

**Comment by janmichek** [comment]
ok, podivam se na to

**Comment by ujovlado** [comment]
Bol by som za to aby sa to spravilo poriadne, kludne koleckom cez indigo-ui, kde by z toho vznikla nova komponenta, ktora sa potom pouzije.

Len pre info, momentalne sa to pouziva na troch miestach.

### Sidebar

![screenshot_2018-08-07_14-54-55](https://user-images.githubusercontent.com/419849/43777011-e123a070-9a51-11e8-99d7-637488257649.png)

### Admin/Account cast v Connection

![screenshot_2018-08-07_14-54-27](https://user-images.githubusercontent.com/419849/43777012-e145f62a-9a51-11e8-94bb-82ab34921eb9.png)

### Projects list

![screenshot_2018-08-07_14-53-47](https://user-images.githubusercontent.com/419849/43777013-e167eb7c-9a51-11e8-8f76-7906c3de8ad3.png)

V kazdom je to teda inym sposobom a chcelo by to mozno nejako zjednotit - resp. aspon povedat, kedy to bude ako vyrenderovane. Tym mam na mysli 2 veci:

- kedy sa to otvori nahor a kedy nadol (to je myslim jasne)
- kedy bude ikonka user vlavo, kedy vpravo, resp. kedy tam nebude ... je to tertaz taky nejednotny mix

**Comment by janmichek** [comment]
Z me navrhuju jednoduchy reseni to zatim udelat jako ellipsis...
Neni tam moc mista. Nasledujici priklad narazi na vizualni maximum. Pripadne bychom to museli vic predelat.

![image](https://user-images.githubusercontent.com/15363559/43777341-cd45b772-9a52-11e8-891f-fb7dc512c29b.png)


V sidebaru delsi email nedela takovej bordel, jako treba na projects-list. Tam to aspon nejak uhne a delsi nazev neoddeli dropup.

**Comment by ujovlado** [comment]
No alebo sa moze rozsirit `.kbc-outer-page>.kbc-outer-container` z povodnych 460px na nieco vacsie

**Comment by janmichek** [comment]
Dobre, do toho by mohlo spadnou zase vic emailu a zobrazit se v plny dylce.
Udelam zatim reseni: rozsireni containeru (500 - 520px) + ellipsis, ok?

**Comment by janmichek** [comment]
Takhle by vypadala zmena, jak jsem navrhoval vyse.

![image](https://user-images.githubusercontent.com/15363559/43782974-d8c6b408-9a60-11e8-8656-819c076bbf71.png)

To cislo 460px je mi nejaky povedomy. Nejaka zakladni responsivita na telefony se resi aspon na 480px (iPhone5 tusim) - 20px padding.
Jenom, ze ted uz se to nevejde na sirku casti telefonu, ale responsivitu jsme nikdy nak moc neresili, takze asi v klidu.

**Comment by janmichek** [comment]
Se symboolem '7' se email vyteckoval. Bez '7' se jeste vysel bez ellipsis.
