### ISSUE TITLE
Check if everything is working after kbc-bootstrap<->master sync

### ISSUE THREAD

**Issue by ujovlado** [keboola/indigo-ui#21]
Spravil som velky merge a rozdiely medzi `master` a `kbc-bootstrap` by uz mali byt iba co sa kodu tyka (build process by mal byt rovnaky).

Zarovne je releasnuta verzia `1.0.0-beta.2`, co som spravil len pokus, ci vsetko fici ako ma.

Bude potrebne skontrolovat:

- ci ti fici storybook ako ma, ked som riesil konflikty, videl som tam, ze niekde sa buildovalo `indigo-storybook.less` namiesto `indigo/less/indigo.less` (to som zmenil aby fical build) ...
- videl som, ze si tam pridal nejake svg sprites, tie bude myslim treba pridat aj do deployu, inac tam myslim nebudu

Ak chces, kludne si to skus naloadovat do kbc-ui.

**Comment by janmichek** [comment]
Fajn, ted jsem to testoval:

1) opravil jsem tu chybu v buildu, uz to ukazuje na spravnej soubor. Indigo se zbuilduje, bezi.
2) po oprave jsem releasnul novej... tag (a verzi v kodu)  v1.0.0-beta.4
3) Uvedl jsem to do package.json v kbc, ale yarn tu verzi nevidi -> Please choose a version of "@keboola/indigo-ui" from this list: (Use arrow keys), takze zatim v kbc to bohuzel nefunguje. 

Moc nevim co s tim, zkousim tady celkem random veci.

**Comment by janmichek** [comment]
Asi bych potreboval vic informaci o fungovani, evidentne se dely zmeny, kterym nerozumim.
Napr.: Naposled jsme si rekli ze tagovani nebudem pouzivat. Ted opet tagovani pouzivame + navic uvadime verzi v package.json. Tohle potrebuju vysvetlit. s3, cloudfront, npm ... nemam tuseni v jakym poradi se co deje. Mozna kdybys udelal nejaky jednoduchy schema, jak to ted funguje, tak by mi to pomohlo.

**Comment by ujovlado** [comment]
> Moc nevim co s tim, zkousim tady celkem random veci.

no lepsie je sa spytat, ked nerozumies, nie skusat random veci ... lahko mozes nieco dojebat ;)

Ten release `v1.0.0-beta.4` netreba robit, ked si nemenil nic, co by ovplyvnilo package ale len "interne" zmeny buildu. Spisem nejaky navod.

Na ten zvysok sa pozriem.

**Comment by janmichek** [comment]
Co se vlastne stane ted kdyz pushnu do masteru?

**Comment by janmichek** [comment]
Jo a ty svg ikony jeste budu ladit, potom to dam spravne do deploye. Ted je to jeste takovy rozdelany.

**Comment by ujovlado** [comment]
Ok, je to popisane tu: https://github.com/keboola/indigo-ui/blob/8c6620bfc5645c5177d365301c8bdc8983515082/README.md ... ked pushnes do mastra, deployne sa storybook, tak ako doteraz. Co pribudlo je len to, ze sa da otagovat aj commit v master branchi a releasne/publishne to indigo-ui (nie storybook!) do npm a s3.

Ten "nepodareny" release som revertol. A ikonky teda riesit nejdem, ked hovoris, ze je to WIP.

**Comment by ujovlado** [comment]
Este ma zaujima `indigo-storybook.less` ... to su CSSka (myslim konkretne tie v tom subore), ktore maju byt dostupne napr. v `kbc-ui` alebo nie?

**Comment by janmichek** [comment]
Dik za navod, uz rozumim lip jak to funguje.

indigo-storybook.less - tam jsou specificky styly pro styleguide. Tyhle styly nechceme v podedenych aplikacich. Zatim je to taky rozpracovany, budu to tunit.

**Comment by ujovlado** [comment]
> Tyhle styly nechceme v podedenych aplikacich.

Super, tak je teraz nasteveny aj ten build/deploy.

Tak tu to asi mozem zavret.

**Comment by janmichek** [comment]
zkusil jsem v kbc vymenit dependecy na  indigo-ui 1.0.0-beta.3 a aplikace se nerozjede - viz screen. Zvlastni.
Zitra to jeste zkusim tweaknout, vic prozkoumat.

![vystrizek](https://user-images.githubusercontent.com/15363559/30332727-5e59bb1c-97db-11e7-9998-43b06c618cd5.PNG)
