### ISSUE TITLE
Search icon position

### ISSUE THREAD

**Issue by ujovlado** [keboola/indigo-ui#214]
Related to #206 

Tym, ze sa zmenila vyska inputu, ikonka je moc nizko.

![screenshot_2018-07-25_11-52-25](https://user-images.githubusercontent.com/419849/43193889-6a79cdbe-9001-11e8-988b-cb4feb22fd32.png)

@janmichek toto sme prehliadli, kukol by si to?

**Comment by janmichek** [comment]
jj podivam
