### ISSUE TITLE
KBC srpen

### ISSUE THREAD

**Issue by jancermak** [keboola/indigo-ui#225]
Vyhradil jsem si srpen — na user feedbacky a jejich pretaveni v issue. 
A obecne zastaveni a zamysleni nad KBC - cil klikatelny prototyp.

All-in-one feedback
https://paper.dropbox.com/doc/KBC-User-Feedback-all-in-one--AK38Xj9ktvKDdXM~03hqJrCRAQ-oHimQ6JYgI9VKY9gb0nA7
-------
Feedback:
GG - revolt.bi
https://paper.dropbox.com/doc/KBC-User-Feedback-1.8.2018-Giuliano-Giannetti--AJI_ZNSnj9rNRjO2xi8PrTZjAQ-3VhQhSJKEc7nXJbpeGJzQ

Jirka Tobolka — Bizztreat
https://paper.dropbox.com/doc/KBC-User-Feedback-1.8.2018-Jirka-Tobolka-Bizztreat.com--AJI_IXlt6hujqbGYNcLPtWydAg-0BrpeIlqvqRrZXe7cFWQq

Michal Procházka — POND5
https://paper.dropbox.com/doc/KBC-User-Feedback-8.8.2018-Michal-Prochazka--AJqaSS1YHkgEPjC8S4evdr3mAQ-U0M9HZegoY9r0GfCGwXvl

Petr Huňka — Rohlík.cz
https://paper.dropbox.com/doc/KBC-User-Feedback-8.8.2018-Petr-Hunka--AJrXBJYqthXCHrmqZPABRaVtAQ-cKKAcSyevpEN7uoVL7xOq

Radek Doležal — Liftago
https://paper.dropbox.com/doc/KBC-User-Feedback-22.8.2018-Radek-Dolezal--AKxYAi7QXBmz8idwbYJ7sYILAQ-qO8wX23mlqpgbR2uJf5bJ

**Comment by janmichek** [comment]
Moje zapisky
https://docs.google.com/document/d/1Q3qHa_e7YOyQj1MSHwmHH0FF9VCK62JsjZRlgEe0Jvc/edit#
