### ISSUE TITLE
Use new version of font-awesome?

### ISSUE THREAD

**Issue by ujovlado** [keboola/indigo-ui#226]
Ked som sa pozrel tu, nevidim vyslovene ikonku ktora by nam chybala a na vsetko sa da najst rozumne alternativa:
https://fontawesome.com/icons

Issues, kde sme to riesili:

- samotne sizing issue: https://github.com/keboola/indigo-ui/issues/178
- tu sme zistili, ze svg sprite je naprd: https://github.com/keboola/kbc-ui/issues/1681
- tu sme riesieli generovanie icon sprite: https://github.com/keboola/indigo-ui/pull/145 (ktory sa ukazal ako naprd.)
- prerobenie na react komponenty: https://github.com/keboola/indigo-ui/issues/170, https://github.com/keboola/indigo-ui/pull/171 a https://github.com/keboola/indigo-ui/pull/176
- pridavali sme nove a ten proces nie je uplne najstastnejsi https://github.com/keboola/indigo-ui/pull/202 (je tam priestor na chybu)
- https://github.com/keboola/indigo-ui/issues/191 (draghandle ikonka je velka, sizing)

Celkovo mi to pride ako zabity cas a moj nazor je tu: https://github.com/keboola/kbc-ui/pull/1839#issuecomment-409524174

Napr. na developer-portal-ui som pouzil font-awesom rovno a ziadny takyto problem som riesit nemusel.

**Comment by odinuv** [comment]
+1

**Comment by kacurez** [comment]
myslis ze by sa font-awesome pouzil na vsetko vratane kbc specific ikonky ako napr input/output mapping, extractor/writer/application..?

**Comment by janmichek** [comment]
Zanalyzoval jsem pouziti ikon v KBC
Nektery maji svuj protejsek v Indigu, jiny jsou nahraditelny, nebo dodelatelny s malo praci (otoceni), nektery nemaji protejsek v indigu

Fa-question-circle = <Icon.Help/>
Fa-calendar = <Icon.Calendar/>
Fa-times = <Icon.Times/>
Fa-user = <Icon.User/>
Fa-search = <Icon.Search>
Fa-play = <Icon.Play>
Fa-check = <Icon.Check>
Fa-plus = <Icon.Plus>
Fa-pencil = <Icon.Edit>
Fa-refresh =  <Icon.Refresh/> 
Fa-eye = <Icon.Overview/> 
Fa-angle-down = <Icon.ArrowDown/>
Fa-undo = <Icon.Refresh/>  [ je zrcadlove obracena]
Fa-angle-right = <Icon.ArrowDown/> [ mame arrow down, jen vec otoceni ikony]
Fa-chevron-right = <Icon.ArrowDown/> [ mame arrow down, jen vec otoceni ikony]
Fa-ellipsis-v =  <Icon.Draghandle/>  [ellipsis-v, nedava smysl, ale ve FA4 uz je fa-grip-vertical]
Fa-database =  <Icon.Storage/>  ??? ale pouzivame to pro Sandboxy, takze <Icon.Sandbox/> 
Fa-files-o = <Icon.Copy/> [pouzivame to pro akci compare, takze by se hodila mozna jina ikona]
Fa-meh-o = [smilik meh pri neuspesnym prihlaseni do db, je to nahraditelny, moc se mi to nelibi]
Fa-info-circle
Fa-code-fork
Fa-clock
Fa-bell
Fa-dropbox
Fa-arrows-v
Fa-share
Fa-reply

**Comment by ujovlado** [comment]
> myslis ze by sa font-awesome pouzil na vsetko vratane kbc specific ikonky ako napr input/output mapping, extractor/writer/application..? 

myslim, ze ked to budeme chciet pouzit tak alternativy najdeme. v base verzii je cca 1.3k ikon, v pro 3.6k.

**Comment by janmichek** [comment]
Asi bude potreba abys to projel z duhy strany - tedy ke 'kbc-icon-*' najit vhodne protejsky  z Font Awesome.
Verim ze alternativy se daji najit, otazka jestli to nechceme mit sity na miru data tematu -> ETL -> KBC.
Myslim ze se da obejit bez ty PRO verze Font awsome. Vetsinou to jsou jen vizualni [flat, thin] variace ikon

**Comment by janmichek** [comment]
Posuneme nejak toto?

**Comment by ujovlado** [comment]
Jo, myslim, ze mozeme ... skusim na to kuknut tento tyzden. Este nez zacnem riesit tie alternativy, skusim si to pokusne instalnut, aby sa nestalo, ze to potom zakape na to, ze format akym to distribuuju nan nevyhovuje alebo tak (co by sa nemalo stat, len pre istotu).

**Comment by jancermak** [comment]
@ujovlado 

Dotaz:
— tyto ikonky http://take.ms/FjN5A by jsi chtel taky resit pres font awesome? 
— ikonka Kebooly - bude resena jako svg?
— toto se netyka svg obrazku  pro empty stavy?

Nazor:
— sobecky - proti - ano chtel bych mit vzhled ikonek pod kontrolou a kdyz neni vhodna mit moznost ji nakreslit a pouzit, zahrava si to s originalitou produktu.
— racionalni - pro - koukam na font awesome a je tam toho hodne, takze alternativy ve vetsine pripadu najdeme.

Technicky na to nazor nemam.

**Comment by ujovlado** [comment]
@jancermak 

> tyto ikonky http://take.ms/FjN5A by jsi chtel taky resit pres font awesome?

idealne ano, zjednodusi sa tym praca

> ikonka Kebooly - bude resena jako svg?

ano, svg, (alebo podobne ako sme doriesili logo na devportal ... t.j. logo + text)

> toto se netyka svg obrazku pro empty stavy?

ak by nieco pre empty stavy slo vyskladat z font-awesome, rad pouzijem to ... inac svg ako doteraz

> — sobecky - proti - ano chtel bych mit vzhled ikonek pod kontrolou a kdyz neni vhodna mit moznost ji nakreslit a pouzit, zahrava si to s originalitou produktu.
> — racionalni - pro - koukam na font awesome a je tam toho hodne, takze alternativy ve vetsine pripadu najdeme.

z pohladu designera ta uplne chapem. ale technicky je to pre nas horsie - chceme tie veci skor vyskladat a priniest "hotovy produkt" ako si nieco stavat na kolene. podobne si nepiseme vlastny framwork a pod. 

chcem ist na to pragmaticky ... a ak sa neskor ukaze, ze to fakt potrebujeme a bude na to cas, preco nie.

**Comment by ujovlado** [comment]
V https://github.com/keboola/developer-portal-ui/pull/525 som testol ako sa s tym robi.

- najprv som skusil klasicke pouzitie (`fas`/`fab`/`far` + `fa-***`) pomocou `<i />` tagu (toto funguje v podstate rovnako ako predtym -  loaduje to aj webfontry).
- potom som skusil inline svg https://fontawesome.com/how-to-use/on-the-web/advanced/svg-javascript-core (ma to vyhody, ze sa daju presne zadefinovat ikonky ktore chceme) -> toto pouzijem na devportal-ui

Momentalne to vidim tak, ze mozeme updatnut na v5, ale zatial imho nebude mozne pouzit tie inline svgcka tak ako v devportal-ui, pretoze mame aj server render. T.j. zatial by to nebolo ako react komponenty.

Co by ale slo je poriesit to JavaScriptom:
https://fontawesome.com/how-to-use/on-the-web/setup/hosting-font-awesome-yourself#using-svgs

Myslim si ale, ze to nemusime mat nutne cez svg (ani teraz nemame) a na svg mozeme switchnut postupne, az sa zbavime tych server render stranok.

Dalsia moznost by napr. bola dohodnut sa, ze v server render strankach tie ikonky nebudu - v tom pripade by stacilo poriesit kbc-ui.

Poskytuju tiez "v4-shims", co zabezpeci, ze budeme mat ikonky z v5, no budu loadnute zapisom v4 - co je bomba, lebo sa da upgradovat postupne.

**Comment by ujovlado** [comment]
Upgrade si viem predstavit takto:

- (optional) prepiseme este par "kbc-icons" na font  awesome 4 (napr. kbc-icon-edit -> fa-pencil, a pod.)
- loadneme font awesome 5 + ich v4-shims (budu naloadovane v5 ikonky s v4 zapisom)
- prepiseme v4 zapis na v5
- vyhodime v4-shims

Jedine co by ostavalo rozhodnut je ci chceme ist cestou svg alebo webfontov. Podla toho sa loadne bud `all.js` alebo `all.css`:
https://fontawesome.com/how-to-use/on-the-web/setup/upgrading-from-version-4#shims

**Comment by ujovlado** [comment]
Este potom pridam ako si predstavujem to mapovanie. Spolu s tym by som asi vyskusal este ten v4-shim.

**Comment by janmichek** [comment]
Muzes se mrknout na toto pls? Navrhnul jsem jak vyresit muj predchozi blok s keboola ikonama - sizing.
https://github.com/keboola/indigo-ui/issues/178#issuecomment-421130594

S pripadnou vymenou ikon si myslim ze nebude technicky problem. To co potrebujeme pri pripadnym prechodu na fa vyresit, je zmenit ikony z keboola ikon na fa - pravdepodobne obecnejsi vyznamy ikon. To si nedokazu uplne predstavit.
https://github.com/keboola/indigo-ui/issues/226#issuecomment-409591132

**Comment by jancermak** [comment]
@ujovlado 
asi jediny zadrhel za me:

> tyto ikonky http://take.ms/FjN5A by jsi chtel taky resit pres font awesome?
> 
> idealne ano, zjednodusi sa tym praca

rikam si ze tim muzeme par lidi zmast kdyz ty ikony vymenime 
do budoucna v pripade prehozeni  menu nahoru na vodorovne a zachovani jenom textovych nazvu by bylo po problemu.

**Comment by ujovlado** [comment]
Ked tak nad tym uvazujem, tych 8 by vlastne mohlo ostat - zmizli by s prerobenim na vodorovne menu ako pises. Nemam s tym teda problem.

**Comment by janmichek** [comment]
Omlouvam se, ale me se to porad moc nezda.
- Ve finale bychom teda nacitali 2 icon sety fa + keboola. ok?
- specificky ikony (ex, wr, ... )  figuruji i jinde nez v hlavni nabidce.
- Z fa bychom pouzili desitky ikon, tisice by zbyly jen jako bloat nacitani (nebo to jde importovat selektivne?)
- To co na fa mame radi, muzem jednoduse ripnout.
- Hlavni zadrhel pouziti keboola ikon - sizing jsem navrhnul, zatim jste na to nereagovali https://github.com/keboola/indigo-ui/issues/178 . Friendly reminder
- Na keboola ikonach se mi libi ze vyzaduje minimum css kodu. Css je cisty zlo xD Taky to bude vic odpovidat branding stylu. 
- S prechodem na webpack 4 mozna odpadne predchozi technologicky zadrhel kompilace - potreba vyzkouset. Momentalne reseni je voser, ne blocker. 
- navrhuju teda odladit sizing a doplnit cca 10 ikon do keboola icon setu https://github.com/keboola/indigo-ui/issues/226#issuecomment-409571460
- v opacnym  pripade porad ocekavam jaky konkretni ikony z fa navrhujete pro vymenu za stavajici. Friendly reminder

**Comment by ujovlado** [comment]
A precital si si prvy komentar tu v issue (https://github.com/keboola/indigo-ui/issues/226#issue-346541592) ? ... Zabili sme na tom imho vela casu a prinos je minimalny.

Z toho co pises skor citim, ze sa to snazis zabit a hladat dovody preco tam tie custom ikonky nechat. Preco preboha robit nieco na kolene, ked existuje hotove odladene riesenie?

> Ve finale bychom teda nacitali 2 icon sety fa + keboola. ok?

nie, vo finale by sme mali len nove font-awesome + keboola ikonky pre sidebar (a po prehodeni na vodorvne menu uz len font awesome, vid. co pise Jack)

> specificky ikony (ex, wr, ... ) figuruji i jinde nez v hlavni nabidce.

je to mozne, viem o casti "deprecated components" na overview, inde som nekukal

> Z fa bychom pouzili desitky ikon, tisice by zbyly jen jako bloat nacitani (nebo to jde importovat selektivne?)

teraz to tak mame, ano, nie je to bohvieco ... ak tam bude aj nacitane vsetko, tak len ako prechodne riesenie. somzrejme to ide pouzit selektivne (pozri si napr. devportal-ui, tam uz to je)

> To co na fa mame radi, muzem jednoduse ripnout.

neviem co myslis

> Hlavni zadrhel pouziti keboola ikon - sizing jsem navrhnul, zatim jste na to nereagovali #178 . Friendly reminder

pozrem sa

> Na keboola ikonach se mi libi ze vyzaduje minimum css kodu. Css je cisty zlo xD Taky to bude vic odpovidat branding stylu.

to iste plati o font awesome ... to je predsa cielom kazdej libky, nie? o brandingu sme sa uz bavili, pridana hodnota imho 0

> S prechodem na webpack 4 mozna odpadne predchozi technologicky zadrhel kompilace - potreba vyzkouset. Momentalne reseni je voser, ne blocker.

a opravis to? lebo zatial som sa s tym mrdal vacsinou ja. Radsej venujem energiu do prechodu na nieco novsie/odladene (uz sa opakujem)

> navrhuju teda odladit sizing a doplnit cca 10 ikon do keboola icon setu #226 (comment)

opat zbytocna praca, mozem radsej riesit upgrade

> v opacnym pripade porad ocekavam jaky konkretni ikony z fa navrhujete pro vymenu za stavajici. Friendly reminder

ok, dam si tu pracu a popisem ti to, aspon uvidis, ze je zbytocne mat vlastne ikony

**Comment by ujovlado** [comment]
ked som dnes riesil tie ikony v sidebare, spomenul som si na toto.

zbytocne by sme hladali alternativy na vsetko, kedze pouzivame tych ikon len par.

![screenshot_2018-12-07_19-37-05](https://user-images.githubusercontent.com/419849/49666193-8c6f4000-fa57-11e8-8b4d-00db94db8a22.png)

spravime to teda takto:

- ostane 8 kbc-icon, co sa pouzivaju v sidebare (tie budu riesene cez font ako doteraz) ako pisem tu https://github.com/keboola/indigo-ui/issues/226#issuecomment-424040405 ... funguje to, nejdem to zatial prerabat ... na svg to mozeme prehodit potom ked nebudeme mat server render stranky, inac by sa to zbytocne komplikovalo
- vsetky zvysne kbc-icon ikony budu nahradene za font-awesome (^ v obrazku prva cast)
- tych 5ks svg ikon co pouzivame nahradime taktisto za font-awesome (^ druha cast v obrazku)
- svg ikonky z indigo-ui pojdu prec

Potom sa uvidi, co dalej. Mohlo by nasledovat:

- pouzitie font-awesome 5 (na developer-portal-ui to uz je - ako react komponenty)
- prerobenie tych 8 ikon na svg (ak ich este bude treba ... ale vyhladovo asi nie, ak sa podari zbavit sidebaru)

**Comment by ujovlado** [comment]
Toto bola vlastne research issue a v https://github.com/keboola/indigo-ui/issues/226#issuecomment-445327982 vidno, ze nam bude stacit par custom ikon (neskor, po presunuti sidebaru, mozno aj ziadne).

Inac je to done.
