### ISSUE TITLE
splash bg - splash description text not visible

### ISSUE THREAD

**Issue by ujovlado** [keboola/indigo-ui#228]
Mozno by to chcelo malicko doladit (dat svetlejsie) ... toto napr. neprecitam:

![screenshot_2018-08-06_17-46-42](https://user-images.githubusercontent.com/419849/43726892-b2edee24-99a0-11e8-8ddc-b8f910b55ed5.png)

**Comment by Halama** [comment]
U tohodle pozadi neni citelny email
![image](https://user-images.githubusercontent.com/903531/43740263-09ff6010-99cb-11e8-8bff-844c77e0b365.png)

**Comment by janmichek** [comment]
ok, jeste to dotunime. Nekde jsem zase nasel ze se text zalamuje prilis brzo

**Comment by janmichek** [comment]
Takhle jsem vic zvednul kontrast (zesvetlil pismo) pro description pod oknem a email.

Taky jsem zmensil pismo na 12px, protoze se text nekde zalamoval.

S tim prachovskym obrazkem budem muset neco vymyslet - tam je reseni suboptimalni - zalezi na rozliseni. Bude se to muset vyresit posunutim orezu, nebo snizenim kontrastu backgroundu.

Celkove by mohli mit obrazky podobnejsi kontrast - nektery jsou tmavejsi, nektery o dost svetlejsi.

![image](https://user-images.githubusercontent.com/15363559/43778963-608e5468-9a57-11e8-83dd-9645de8952b2.png)

**Comment by janmichek** [comment]
Zatim bych to mergnul a ty obrazky poresil v nasledujici issue, kterou zalozim. Nevim jestli se k tomu zitra s Jackem dostaneme. Mame nabitej program.

**Comment by janmichek** [comment]
followup -> https://github.com/keboola/indigo-ui/issues/232
