### ISSUE TITLE
splash bg - unify bg contrasts

### ISSUE THREAD

**Issue by janmichek** [keboola/indigo-ui#232]
S tim prachovskym obrazkem budem muset neco vymyslet - tam je reseni suboptimalni - zalezi na rozliseni. Bude se to muset vyresit posunutim orezu, nebo snizenim kontrastu backgroundu.

Celkove by mohli mit obrazky podobnejsi kontrast - nektery jsou tmavejsi, nektery o dost svetlejsi.

**Comment by janmichek** [comment]
@jancermak mame nejaky novy pouzitelny fotky z posledniho offsitu? pls mrkni co by se dalo pouzit.
https://photos.google.com/share/AF1QipMJtjj--_NhlggyGX6N7dq7klWbI7anVcsQC5LfO4K6WvpkqQfhSzvj_B4ZQAozlA?key=a0tUamZhY3lYcE1qRjU1QmQ4ZWtHTGF3TVJPRVVB

**Comment by Halama** [comment]
slowmotion marc ve vlaku na pozadi?:)
