### ISSUE TITLE
select project tuning

### ISSUE THREAD

**Issue by janmichek** [keboola/indigo-ui#235]
Zkontrolovat jestli neobsahuje nevyuzite styly
https://github.com/keboola/indigo-ui/pull/234#issuecomment-411148874

Fix text ellipsis
![image](https://user-images.githubusercontent.com/15363559/43824174-92cf5766-9af1-11e8-80fe-b42928b4103a.png)

**Comment by janmichek** [comment]
Pred
![image](https://user-images.githubusercontent.com/15363559/43894607-f3186338-9bd2-11e8-91e9-c6d7a035e15e.png)

Po
![image](https://user-images.githubusercontent.com/15363559/43894618-f88732cc-9bd2-11e8-970d-096a527ae005.png)

Pridal jsem docasny styly a checknul pro stary / novy markup. Vse vypada ok

**Comment by janmichek** [comment]
+ jsem zkontroloval a upravil nepouzivane styly

**Comment by ujovlado** [comment]
@janmichek radsej poziadaj o review ... netreba ma tam assignovat, pokial na tom nemam nic robit ;)

**Comment by janmichek** [comment]
ups, sorry jsem se ukliknul. Melo to byt co pises
