### ISSUE TITLE
Searchbar fixes

### ISSUE THREAD

**Issue by janmichek** [keboola/indigo-ui#240]
Uz tomu nemuzu dyl prihlizet .]

Je tam nekolik bugu a dost nejednoty. Ten element je dost viditelny a pouzivany
- [x] vyscreenovat pouziti
- [x] sjednotit layout
- [x] sjednotit focus styl
- [x] srovnat ikonu
- [x] vyhodit bootstrap classy (kde neni potreba - row, ...)
- [x] zdokumentovat v indigu - na zaklade screenu

**Comment by ujovlado** [comment]
Neviem ci to chapem z tych checkboxov, no mohla by s toho vzniknut nova komponenta v indigo-ui. napr. `SearchBar`. Mala by nove styly a podporovala by par "eventov' ako napr. `onChange` pripadne aj `onSubmit`.

**Comment by ujovlado** [comment]
T.j. toto by preslo do indigo-ui:
https://github.com/keboola/kbc-ui/blob/2122969f560ad38ad98a6ec103c5cdfa47ae773b/src/scripts/react/common/SearchRow.jsx

**Comment by janmichek** [comment]
pouziti projects-list
![image](https://user-images.githubusercontent.com/15363559/44214612-debae700-a170-11e8-855c-33acbdfa9d8a.png)

pouziti sidebar projects
![image](https://user-images.githubusercontent.com/15363559/44214649-f6926b00-a170-11e8-8d46-58573a007500.png)

pouziti ex, tr, wr, orch
![image](https://user-images.githubusercontent.com/15363559/44214717-1590fd00-a171-11e8-8042-305effbe4afe.png)

pouziti jobs list
![image](https://user-images.githubusercontent.com/15363559/44214759-2c375400-a171-11e8-8a7b-e9c86b21334c.png)

pouziti config search
![image](https://user-images.githubusercontent.com/15363559/44214811-483af580-a171-11e8-8e12-94d8d317420d.png)

pouziti config rows
![image](https://user-images.githubusercontent.com/15363559/44214855-61dc3d00-a171-11e8-8854-354a03c0251c.png)

**Comment by janmichek** [comment]
@ujovlado ano, presne tak

**Comment by ujovlado** [comment]
ok, super
