### ISSUE TITLE
SAPI Error Window Text Overflow

### ISSUE THREAD

**Issue by ujovlado** [keboola/indigo-ui#246]
_From @milanveverka on January 23, 2016 20:12_

The text doesn't wrap up in the error window:

https://www.evernote.com/l/ACDhlRC3BatHUZr7vMKo0i65g-MG4TlMzZA

_Copied from original issue: keboola/kbc-ui#471_

**Comment by janmichek** [comment]
Jasny no .] bs freesyle. Neco se s tim pokusim udelat

**Comment by natocTo** [comment]
Zavírám. Podle obrázku se týkalo staré storage console.
