### ISSUE TITLE
Missing padding in Create table window

### ISSUE THREAD

**Issue by ujovlado** [keboola/indigo-ui#247]
_From @Matejkys on August 25, 2015 15:16_

Ahoj,

při vytváření nové tabulky v SAPI není u "Create from" nastavený padding, tak je to přitisklý k okrajům. Viz. screenshot.

![image](https://cloud.githubusercontent.com/assets/12933713/9470619/feb05022-4b4c-11e5-9612-cf5cf14d06bb.png)

_Copied from original issue: keboola/kbc-ui#355_

**Comment by natocTo** [comment]
Toto zavírám, se týkalo tuším staré storage console.
