### ISSUE TITLE
Smaller margin on AlertBlock?

### ISSUE THREAD

**Issue by ujovlado** [keboola/indigo-ui#248]
Momentalne je tam 20px, tuna trosku vidno, ze to nesedi:
https://github.com/keboola/kbc-ui/pull/1871#issuecomment-415011974

Nemalo by tam byt menej? 16?

**Comment by janmichek** [comment]
Sorry ale nevykoukal jsem co myslis? Na prvni pohled me nic neurazi

**Comment by ujovlado** [comment]
![screenshot_2018-08-22_14-43-04](https://user-images.githubusercontent.com/419849/44464022-db64a700-a619-11e8-9b7a-ccaf37ffa0a3.png)

**Comment by janmichek** [comment]
Jasny uz to vidim. Dobrej mindfuck .] Melo by se to resit na urovni layoutu, ne komponenty.

**Comment by janmichek** [comment]
Vypada to, ze by to nemel byt prob. Spravne je to pouzito napr tady: 
![image](https://user-images.githubusercontent.com/15363559/49724739-4e963580-fc6a-11e8-9a9f-7900ef5884b8.png)

Pokud nekde ulitavaji pixely, tak to bude spis nespravnym pouzitim, spis nez komponentou samotnou
