### ISSUE TITLE
NotAvailable component (or styles at least)

### ISSUE THREAD

**Issue by ujovlado** [keboola/indigo-ui#249]
This can be really useful in situations when we want to say something is not available.

Context:
- https://github.com/keboola/kbc-ui/pull/1915#issuecomment-415044469

It can be solved by separate component or only a class.

Proposal:

![screenshot_2018-08-22_16-11-09](https://user-images.githubusercontent.com/419849/44468704-1c62b880-a626-11e8-8516-27ca3201c12a.png)

**Comment by ujovlado** [comment]
Asi by stacilo aby to bola zatial len nejake classa, ktoru dam neblokovemu elementu. :)

**Comment by ujovlado** [comment]
Potom bude treba vyhodit to `em` z keboola/kbc-ui#1915

**Comment by janmichek** [comment]
jo - italic stylu se chceme zbavit v ramci 2. vlny upravy fontu https://github.com/keboola/indigo-ui/issues/189

**Comment by ujovlado** [comment]
Skor som narazal na to, ze to tam teraz pribudlo. Nechame to tak?

**Comment by janmichek** [comment]
V soucasnym stavu je mi to jedno. Vyskytuje se to na vice mistech.

**Comment by janmichek** [comment]
Tak jo, poustim se do toho. Nejdiv prozkoumam ruzny empty stavy (je to ruzne rozesety po aplikaci) a potom tady zkusim pripravit vizualni navrh

**Comment by janmichek** [comment]
Vetsina empty statu se da v kbc vyhledat pomoci retezcu 'N/A', 'No ', 'text-muted', '`<em>`'

**Comment by janmichek** [comment]
**Analyza a navrhy**

1) Takhle jsem nasel ruzny pouziti 'N/A' jako empty stavu:

![image](https://user-images.githubusercontent.com/15363559/49875386-2f8dd400-fe21-11e8-9638-e67e8862d0d0.png)

![image](https://user-images.githubusercontent.com/15363559/49875391-3288c480-fe21-11e8-82a1-43458b7def21.png)

![image](https://user-images.githubusercontent.com/15363559/49875423-416f7700-fe21-11e8-9f05-9290ec1933bd.png)

Tady to bude easy, to navrhuju sjednotit pomoci `<NotAvailable/>` komponenty v indigo UI aby to vypadalo jednotne takto
![image](https://user-images.githubusercontent.com/15363559/49875713-fa35b600-fe21-11e8-9609-45ced0d7e214.png)

```

element.style {
    font-style: italic;
    color: #5d6982;
}
```


2) Potom tu jsou vic okecavaci empty stavu:
![image](https://user-images.githubusercontent.com/15363559/49875890-703a1d00-fe22-11e8-94b2-268bb1e30bab.png)

![image](https://user-images.githubusercontent.com/15363559/49875898-75976780-fe22-11e8-98a5-9c75543cd792.png)

![image](https://user-images.githubusercontent.com/15363559/49875903-78925800-fe22-11e8-84b4-c45322655140.png)

![image](https://user-images.githubusercontent.com/15363559/49875916-7e883900-fe22-11e8-877b-4c1bdc61ba2d.png)

K tomu navrhuju obslouzit to komponentou vyse, rozsirenou o props `<NotAvailable text="No Description"/>`


3) zatim neresim ale nektery empty stavy jsou reseny obrazkama. Coz mi prijde dobry, ale zatim bych neobsluhoval touto komponentou
![image](https://user-images.githubusercontent.com/15363559/49876321-6a910700-fe23-11e8-8b64-335b548fdba4.png)

4) zacal bych to teda prevlekat dle popisu vyse, je toho v aplikaci docela dost a je mozny ze budu zavadet jeste jinou property na rozliseni, pokud si neporadim nijak elegantneji.

**Comment by ujovlado** [comment]
Ideme tam teda davat novy rez len kvoli `N/A`? alebo na to kasleme?

**Comment by janmichek** [comment]
Ne, nedelal bych to. Myslim ze bohate staci ta prohlizecova emulace, nevypada to nijak zubate. Koukam na Chrome, FF, Edge

**Comment by ujovlado** [comment]
ok, super :)
