### ISSUE TITLE
Version 2 plan

### ISSUE THREAD

**Issue by ujovlado** [keboola/indigo-ui#26]
First:

- [x] push current `master` as `v1` (to keep changed for further use)
- [x] force-push `kbc-bootstrap` to `master`
- [x] provide `v1` for "browsing" purposes // done: https://indigo.keboola.com/v1
- [x] update readme to match planned v2
- [x] add manifest generator (can be copied from `kbc-ui`)
- [x] update build process to match planned v2
- [x] start tagging as v2 from `master` (former `kbc-bootstrap`)
- [x] automated registering to Connection
- [x] check if everything is working when registered to local Connection

Next:

- migrate `kbc-react-components` (then use it in `kbc-ui` -> this will be the first test of v2 package which provide components
- unify components, styles, get rid of styled native bootstrap components, etc.
- start writing new components (all custom classes prefixed with `indigo-ui` ... later we can migrate to better solution: e.g "styled components" or CSS local variables, etc.)

**Comment by ujovlado** [comment]
Pripravne veci ready, este to par krat odskusam, skusim loadnut do connection a tiez do kbc-ui.

**Comment by ujovlado** [comment]
Posledny check, potom tagujem `v2.0.0`.

**Comment by janmichek** [comment]
@ujovlado ok, jestli chces pomoct neco testnout, dej vedet

**Comment by ujovlado** [comment]
Ani nie, len som to chcel pre istotu este diffnut :)

```
vlado@yoda:~/workspace/keboola/indigo-ui/indigo-ui-assets/indigo-ui$ sha1sum v0.1.6-0-g12c4dd0/css/kbc.css 
8ea667d1b8f96e7994676d99b7ad76d7d695daf4  v0.1.6-0-g12c4dd0/css/kbc.css

vlado@yoda:~/workspace/keboola/indigo-ui/indigo-ui-assets/indigo-ui$ sha1sum v2.0.0-rc.6-0-g3fa799a/css/indigo.css 
8ea667d1b8f96e7994676d99b7ad76d7d695daf4  v2.0.0-rc.6-0-g3fa799a/css/indigo.css

vlado@yoda:~/workspace/keboola/indigo-ui/indigo-ui-assets/indigo-ui$ sha1sum v0.1.6-0-g12c4dd0/css/kbc.uncompressed.css 
27b40aea923c8fe489b0291eb90234a85795c121  v0.1.6-0-g12c4dd0/css/kbc.uncompressed.css

vlado@yoda:~/workspace/keboola/indigo-ui/indigo-ui-assets/indigo-ui$ sha1sum v2.0.0-rc.6-0-g3fa799a/css/indigo.uncompressed.css 
27b40aea923c8fe489b0291eb90234a85795c121  v2.0.0-rc.6-0-g3fa799a/css/indigo.uncompressed.css
```

**Comment by ujovlado** [comment]
Len pre ilustraciu:

![screenshot_2017-12-05_14-00-32](https://user-images.githubusercontent.com/419849/33608394-b0ad6e38-d9c4-11e7-9b16-b7b0d2c68f3b.png)

**Comment by ujovlado** [comment]
Fixed in https://github.com/keboola/indigo-ui/commit/b3699a3da8c7a01b0212d8b30f1425f2057459d7
