### ISSUE TITLE
SearchBar - dark theme has different font-size + padding

### ISSUE THREAD

**Issue by ujovlado** [keboola/indigo-ui#261]
Looks like it has different font-size and some padding.

![screenshot_2018-09-13_12-34-00](https://user-images.githubusercontent.com/419849/45483471-4e60c980-b751-11e8-8ce0-57e8b12ea778.png)

![screenshot_2018-09-13_12-34-23](https://user-images.githubusercontent.com/419849/45483488-5caee580-b751-11e8-8cbf-7a441d948b3d.png)

**Comment by janmichek** [comment]
Tady jsem si ulehcil praci a neudelal to systemove.
Theme by se melo vyresit na jiny urovni (variables atd...).
Vzhledem k tomu ze to ma jen jedno misto pouziti tak jsem to dal zatim k inverse classe.
spravne vyresit znamena zacit psat theme a upravit to v sidebaru

**Comment by ujovlado** [comment]
Toto mi uz nerobi vyzerat to tak
