### ISSUE TITLE
Init Jakub

### ISSUE THREAD

**Issue by ujovlado** [keboola/indigo-ui#265]
V readme tohto projektu (https://github.com/keboola/indigo-ui) som sa snazil popisat ako to s tymto repozitarom funguje, ak narazis na nieco nejasne pri rozbehani, kludne to dumpni sem.

**Comment by natocTo** [comment]
Instalace a spuštění proběhlo v pohodě.
Zkoušel jsem si hned pustit i testy 'yarn test' a 'yarn stylelint'. Oba příkazy proběhli v pohodě.
Podívám se na to víc v rámci review co tam mám jinde.

**Comment by natocTo** [comment]
Koukám že se mi generují ikonky do indigo/components/icons. To ale pak nebudu pushovat že, nemělo by to být v ignore nebo to asi můžu prostě ignorovat sám.

Ještě zkouším zobrazit novou komponentu v tom storybook. Přidal jsem novou složku do staries, přidal tam index.js. Ale po nastarování storybook to tam furt nevidím. Je potřeba to někde registrovat?

**Comment by ujovlado** [comment]
A pridaval si nejake ikonky alebo tak? Oznacuje ti tie subory ako zmenene?

**Comment by ujovlado** [comment]
> Ještě zkouším zobrazit novou komponentu v tom storybook. Přidal jsem novou složku do staries, přidal tam index.js. Ale po nastarování storybook to tam furt nevidím. Je potřeba to někde registrovat?

nasiel si to nakoniec ano?

**Comment by natocTo** [comment]
Jo zapomněl jsem to tu dopsat. Nakonec jsem vše dohledal.

Zkusil jsem si i to použití v kbc-ui. Takže možná to tu můžeme zavřít.

**Comment by ujovlado** [comment]
ok, tak to tu zavrem, ked si s tym +- zoznameny.

**Comment by janmichek** [comment]
@natocTo Povedlo se ti lokalni prolinkovani indigo -> kbc pomoci "yarn link" ? Za me to je velkej timesaver.

**Comment by ujovlado** [comment]
dobra pripomienka ... tiez to skusim ... uz by to asi mohlo ficat, ked mame na kbc-ui webpack 4 :+1:

**Comment by natocTo** [comment]
Jo, včera jsem to testoval pomocí "Yarn link" a běželo to.
