### ISSUE TITLE
User link - focus bug

### ISSUE THREAD

**Issue by ujovlado** [keboola/indigo-ui#269]
![screenshot_2018-09-18_20-28-15](https://user-images.githubusercontent.com/419849/45708380-96348600-bb81-11e8-9f33-e40edb9cebca.png)

**Comment by janmichek** [comment]
Zkusim to prozkoumat. Takhle na prvni oklikani jsem moc nezjistil.

**Comment by ujovlado** [comment]
Zreprodukovat to ide lahko, navigujes po stranke tabom alebo tak ako v screenshote ^

```
.nav>li>a:hover, .nav>li>a:focus {
    text-decoration: none;
    background-color: #fff;
}
```

**Comment by janmichek** [comment]
Je to videt uz na urovni samostatny komponenty - indiga
https://indigo.keboola.com/?selectedKind=ExternalLink&selectedStory=ExternalLink&full=0&down=1&left=1&panelRight=0&downPanel=storybook%2Factions%2Factions-panel

Pravdepodobny reserni: https://stackoverflow.com/a/44410281/358804
Jdu ho vyzkouset.

**Comment by janmichek** [comment]
Problem je ze tam zustane viset focus state, ktery by tam byt nemel.
Budiz, klido to vyresim takhle, ale nevyresi to podstatu problemu. Pro me snadnejsi reseni.
Jeste v tech focus stylech teda visi outline.

**Comment by ujovlado** [comment]
> Problem je ze tam zustane viset focus state, ktery by tam byt nemel.

a nie je toto default chovanie browsera? preco by tam ten focus nemal ostat?

**Comment by ujovlado** [comment]
Do toho issue som to teda nenapisal - moja chyba, no myslel som, ze vieme o com sa bavime :)

**Comment by janmichek** [comment]
hm, dobra otazka. Zacal jsem to paralelne zkoumat.
Je to tak jak pises, pripada mi to dost spis matouci. Myslel jsem ze nove otevreny tab ti vezme focus.
Jdu fixnout ty styly.

**Comment by janmichek** [comment]
Mozne me zmatli i ten nazev issue. Zacal jsem resit Focus bug. Nicmene reseni v PR ^^^
