### ISSUE TITLE
najit font misto helveticy 

### ISSUE THREAD

**Issue by janmichek** [keboola/indigo-ui#27]
(typography.com - pair fonts)

**Comment by jancermak** [comment]
Dle slack komunikace — nechme jako alternativu Arial.

Prosel jsem typography jedinej kterej me zaujal je tento — https://www.typography.com/fonts/ringside/overview/

**Comment by janmichek** [comment]
Vypada dostatecne vizualne jednoduse, za me ok. Jeste by bylo fajn to videt v realnym prostredi kbc. Umis to nejak nasimulovat v browseru?

**Comment by ujovlado** [comment]
V jednej z verzii `kbc-bootstrap` bol plan pouzit Roboto (google web fonts). Ale kvoli jednemu "typo" sa to do produkcie nedostalo. Mal aj hodne roznych rezov.

**Comment by janmichek** [comment]
Roboto mi vizualne taky ladi k tomu co chcem, nicmene neni v nabidce typography.com

**Comment by janmichek** [comment]
V tvym invision projektu to teda nevidim, ale zatim je to jedno

**Comment by jancermak** [comment]
Ringside — nejsem schopen ho z typogrqphy stahnout do pocitace - jen za penize. Nikde jsem ho nenasel abych si ho mohl pujcit - pro me do sketche na navrhy.

Z tohoto duvodu navrhuji jet — Gotham & Ariel 

Pripadne roboto — to je na google font free, je ke stazeni

**Comment by janmichek** [comment]
beru si cas do pristiho tejdne na rozmyslenou/rozseknutelnou

Ringside - blby ze s tim nemuzem pracovat lokalne - nebo zaplatime?
Arial - me to urazi koukat se na takhle basic font, vypada to lacine
ROboto - hezky, ale je tu technologicky blocker typography.com/google fonts

**Comment by ujovlado** [comment]
> Arial - me to urazi koukat se na takhle basic font, vypada to lacine
 toto podpisem, nie je to pekne zladene (ale na druhu stranu, napr. taky Github, Twitter takto ficia stale :) )

> ROboto - hezky, ale je tu technologicky blocker typography.com/google fonts
co myslis tym technologicky blocker?

**Comment by ujovlado** [comment]
> Z typography.com tahame pres cdn font Gotham. Roboto tam neni. Pripadne bychom ho museli nalinkovat z Google fonts. Potom ale ztraci mit vyhodu ta aplikace na fonty, ne? Na google.fonts zase neni Gotham, ktery je nas brand font.

no osobne tam technologicky problem nevidim ... skor len ci nam vadi dalsi font source alebo nie ...

> Jack potrebuje font v .otf/woff kvuli Sketchi. Font Gotham je rozsirenejsi tak jsme ho 'ripli' pro vyvojovy ucely. Novy font Ringside neni zas tak rozsireny. Problem je v tom ze z typography.com si to muzes stahnout lokalne jen po zaplaceni. Zkusim se jeste optat padaka jestli by nechtel zainvestovat do toho fontu, at s tim Jack muze radit. 199$ https://www.typography.com/fonts/ringside/styles/screensmart/

no ak to stoji len na tom, ci to niekto cvakne je to imho "no brainer" -> kupit :)

> Kdyz kouknes do css inspectoru, tak GH uz nepouziva Arial, Twitter koukam taky ne. Nicmene je to stejne jedno.

myslel som to tak, ze vo vela pripadoch ti tam skonci Arial (sans serif alebo ina lokalna alternativa) -> t.j. idu po systemovych fontoch, co ma vyhody (napr. u mna to je arial)

**Comment by janmichek** [comment]
Font jsme se domluvili s padakem ze koupime, tak tim se vyresi spousta veci.

**Comment by janmichek** [comment]
jeste nez zakoupime, tak provedu posledni check - cvicne naimportuju font RIngside do dev (local) verze kbc

**Comment by janmichek** [comment]
https://www.typography.com/blog/fonts-for-complex-data

**Comment by janmichek** [comment]
@jancermak  Nejlip mi z toho clanku^^^ vychazi font 'Whiney Pro'. Ma nejmin brutalni patku pro monospace znak '1'. ZKusim to cvicne naimplmentovat do kbc

**Comment by ujovlado** [comment]
OK, da sa to spravit dvoma sposobmi.

1. Nahras tie fonty  manualne do aws s3. Neviem ale ci tam mas account, no prinajhorsom ti niekto vygeneruje credentials, ktore na to mozes pouzit. Nahrava sa to do bucketu `misc-ui-assets`

2. Pushnes to do repozitara (co som teraz zbuchol) sem:
https://github.com/keboola/cloud-typography-fonts (checkni readme)

Odporucal by som to druhe, s nicim sa nemusis dalej babrat.

**Comment by ujovlado** [comment]
Tie fonty som republishol.

**Comment by ujovlado** [comment]
@janmichek este teda jedna vec. Ak to skusas lokalne, zmen si to tu:

https://github.com/keboola/kbc-ui/blob/fbc9447992f0431fd942e84b904f38033800abed/index.html#L6

**Comment by janmichek** [comment]
Jj cool, lokalne vim jak to nahodit.

Ted jsem zkousel republishnout font - zapomel jsem nastavit monospaced cisla per font.
Po ceste jsem udelal par blbosti a trochu jsem se ztracel, tak jsem updatnul readme s How To republish for Dummies xD

**Comment by janmichek** [comment]
https://github.com/keboola/cloud-typography-fonts/blob/master/README.md

**Comment by janmichek** [comment]
Dal jsem na lokalu vedle sebe fonty Gotham (tucnejsi, Keboola font) a Whitney (citelnejsi, pro content, ma monospaced cisla).
Ted neresim co ma byt jakym fontem - nadpisy, buttony, ... To urcite bude jinak.

Jde mi o to jak vypadaji fonty vedle sebe. S vysledkem jsem spokojen, jeste to projackujeme s Jackem

![jobs1](https://user-images.githubusercontent.com/15363559/40061044-4bd9b03a-5858-11e8-8613-c52c1c1bd3a6.JPG)
![compo1](https://user-images.githubusercontent.com/15363559/40061045-4c06b5f8-5858-11e8-9513-1d13c2c7503e.JPG)
![jobdet1](https://user-images.githubusercontent.com/15363559/40061046-4c2c8d32-5858-11e8-8bd9-a1c866dc2c44.JPG)
![trsf1](https://user-images.githubusercontent.com/15363559/40061047-4c52dee2-5858-11e8-9753-12441e641891.JPG)

**Comment by ujovlado** [comment]
Toto hore su teda vsetko Whitney?

**Comment by janmichek** [comment]
jj, Whitney + Gotham

**Comment by ujovlado** [comment]
vyzera to celkom dobre. ozaj, neskusal si aj font-weight 300? ci to sa zavrhlo a ideme normalne na 400?

**Comment by janmichek** [comment]
U kteryho fontu konkretne myslis? Momentalne jsem neresil font-weight, spis jsem zkoumal jak vypadaji stejny znaky ruznych fontu. Na weight se teda jeste zamerim. Predpokladam ze ti jde o trochu tenci nadpisy.

Pro screeny jsem pouzil nasledujici styly

`
body{
font-family: "Whitney SSm A", "Whitney SSm B";
font-style: normal;
font-weight: 400;
}

h1, h2, h3, h4, h5, h6{
font-family: "Gotham Rounded A", "Gotham Rounded B";
font-style: normal;
font-weight: 500;
}`

**Comment by ujovlado** [comment]
ee, nemyslel som nic konkretne, len ma zaujimalo, ze aky je ciel s tymi rezmi ... teraz je tam (v produkcii) teda ta 300ka helvetica a pod.

Tak  som chcel vediet, ci tam bude opat 300 (neriesim si gotham alebo whitney) alebo sa chysta switch na 400ku a uz nebude "default" taky tenky.

**Comment by janmichek** [comment]
Ted to rict nedokazu jestli pouzijeme 300 nebo 400. Zalezi jak to bude vizualne vypadat. Projackujeme to. To co je ted v produkci je irelevantni, kdyz se to renderuje na kazdy platforme jinak. S nasazenim novy kombinace fontu, se opet snizi wtf index xD

**Comment by ujovlado** [comment]
super, som rad ze sa to pohne

**Comment by jancermak** [comment]
@janmichek @ujovlado — koukam na ty screenshoty a libi se mi to!  Jeste se na to dneska kouknu u tebe pokud to mas nekde nahozeny. Zkousel jsem ten font nekde stahnout. Ale nenasel jsem ho (lisi se v cislech) Budu potrebovat koupit licenci na jeden pocitac.

**Comment by janmichek** [comment]
Bomby, ty fonty mi k sobe sedi. Ted asi bude potreba rozseknout = upravit v kbc - kde bude jaky html element a jaky bude mit styly a tloustky fontu - typicky -button, headingy, labely ...

**Comment by ujovlado** [comment]
Mne by sa celkom pacilo nieco podobne ako si navrhoval tu: https://github.com/keboola/indigo-ui/issues/27#issuecomment-389196453 -> t.j. vsetky headings dat Gotham (rez by som nechal na Jacka) a zvysok dat Whitney (asi kobinacia 300+400 alebo len regular 400). Som zvedavy :)

**Comment by janmichek** [comment]
Odkladam Netrideny poznamky k jackovani, Nejlepsi bude kdyz k tomu spolecne sednem a rovnou to pofixujeme

Gotham v logu kebooly je fw 500.
Na nadpisy zatim pouzivam Gotham fw 500
Na button zatim pouzivam Gotham fw 300.
Budeme pouzivat Gotham fw 400?
Nektery mensi nadpisy vypadaji brutalne, predvedu.
Mozna si predem vydefinujeme styly nadpisu. Budeme pouzivat i fw 300?
V aplikaci se vyskytuje kurziva (vetsinou pro description) nema to zatim moc zadnou jedntu. Chceme zachovavat (importovat rez) kurzivu?
Nektery ovladacy prvky (buttony ale styl linku) chceme jakym fontem? Napr v detailu extractoru, buttony vpravo.
Styly se promitnou i pripouziti 'Markupu'.
checknout formularovy labely napr extractors/keboola.ex-aws-s3
Uprava GM, nemusi tam byt tolik pregothamovano

**Comment by janmichek** [comment]
Probrano s Jackem:

Udelam ted upravy v KBC, pristi tyden na to mrknem s Jackem a pokusime se co nejvic veci zdokumentovat a ustalit. 
Ted je to v KBC nesourody, jak stylama tak kodem, prestylvanim atd.


Guide na predelani:

- Nadpisy - Gotham 700
- buttony - Gotham 500
- texty - Whitney 400
- text bold - Whitney 700 (vyzkousime i 600)

Nadpisy vzdy vetsi nez texty.
U mensich nadpisu je mozne dat Gotham 500
Formulare: Nazev kategorie bude Nadpis label formularoveho prvku Whitney (ale mensi nez nadpis kategorie.
Akce - napr. v detailu transformace -> Gotham
GM links - Gotham
GM texty - Whitney
GM seznam - Gotham

(bacha v GM je jeste Gotham 300 - zdokumentovat)

**Comment by janmichek** [comment]
Odkladam co ve stredu projet s Jackem
- zvalidovat pouziti v Developer portalu
- 
- 
-

**Comment by janmichek** [comment]
Kolecko projackovany, ukladam si co upravit, potom tady Jackovi pripravim screeny.
- mensi nadpisy mohou mit Gotham 500 ( od jaky velikosti?)
- devportal - zkusime implementovat whitney na normalni txt
- gm lekce buttony Whitney
- description -> save -> fixnout btn
- sjednotit nazvy entit v gridech
- navigace sjednotit
- header jobu sjednotit

**Comment by ujovlado** [comment]
S tym devportal daj potom kludne vediet/zaloz issue - pomozem s tym. Fonty tam su separatne (uvidis v cloud typography)

**Comment by janmichek** [comment]
https://github.com/keboola/developer-portal/issues/205

**Comment by janmichek** [comment]
@jancermak posilam slibovany screeny po upravach + archiv.
Zkus to zvalidovat mezi sebou a navrhnout pripadne upravy

[fontscreens.zip](https://github.com/keboola/indigo-ui/files/2059144/fontscreens.zip)


<img width="886" alt="ex1" src="https://user-images.githubusercontent.com/15363559/40795013-11ad1db0-6501-11e8-8fb0-c90245c7688d.PNG">
<img width="899" alt="ex2" src="https://user-images.githubusercontent.com/15363559/40795014-11ce9238-6501-11e8-9c48-e6e3248f1321.PNG">
<img width="899" alt="ex3" src="https://user-images.githubusercontent.com/15363559/40795015-11f6d9c8-6501-11e8-8b82-72d38f4d8687.PNG">
<img width="885" alt="ex4" src="https://user-images.githubusercontent.com/15363559/40795016-12168016-6501-11e8-9fbc-c8c9674a3d64.PNG">
<img width="986" alt="gm1" src="https://user-images.githubusercontent.com/15363559/40795017-12421a32-6501-11e8-9de2-34296abb7f8d.PNG">
<img width="1053" alt="gm2" src="https://user-images.githubusercontent.com/15363559/40795018-12635364-6501-11e8-9f38-b6e63fcf3b19.PNG">
<img width="886" alt="jobs1" src="https://user-images.githubusercontent.com/15363559/40795019-1281c61e-6501-11e8-8fd2-6d25bf5ebfb2.PNG">
<img width="887" alt="jobs2" src="https://user-images.githubusercontent.com/15363559/40795020-12e911c0-6501-11e8-9473-dc6e0b530bed.PNG">
<img width="884" alt="limits" src="https://user-images.githubusercontent.com/15363559/40795021-130f536c-6501-11e8-9831-4f6de032544a.PNG">
<img width="897" alt="orch1" src="https://user-images.githubusercontent.com/15363559/40795022-134122b6-6501-11e8-98dc-a92a37d227cf.PNG">
<img width="889" alt="orch2" src="https://user-images.githubusercontent.com/15363559/40795023-1379b6e4-6501-11e8-9833-33706269abf6.PNG">
<img width="888" alt="over" src="https://user-images.githubusercontent.com/15363559/40795024-13ae1038-6501-11e8-920c-cf5afcbf96b6.PNG">
<img width="891" alt="pow" src="https://user-images.githubusercontent.com/15363559/40795027-13ea41ca-6501-11e8-8f0b-16d1abd1d6a7.PNG">
<img width="197" alt="sidebar" src="https://user-images.githubusercontent.com/15363559/40795028-14277c0c-6501-11e8-84e2-79234129975f.PNG">
<img width="885" alt="tr1" src="https://user-images.githubusercontent.com/15363559/40795030-144c35c4-6501-11e8-9f3f-d53b75789c45.PNG">
<img width="886" alt="tr2" src="https://user-images.githubusercontent.com/15363559/40795031-1486d26a-6501-11e8-9509-a34bb0d6c795.PNG">
<img width="886" alt="wr1" src="https://user-images.githubusercontent.com/15363559/40795032-14d0ea1c-6501-11e8-8a88-e002029097bb.PNG">

**Comment by jancermak** [comment]
Ahoj co me napadlo zakresluju do screenu...
![ex1 png 2018-06-06 12-18-58](https://user-images.githubusercontent.com/1826442/41032592-2d8469da-6984-11e8-853b-4a4a6eaaf802.png)
![image](https://user-images.githubusercontent.com/1826442/41038447-7a18f4de-6996-11e8-8199-4a707fb5a556.png)
![monosnap 2018-06-06 14-33-25](https://user-images.githubusercontent.com/1826442/41038512-b76cd7e2-6996-11e8-9330-fc0a84bea955.png)
![image](https://user-images.githubusercontent.com/1826442/41038795-b3e4cf20-6997-11e8-8348-3e4c5aa91a53.png)
![image](https://user-images.githubusercontent.com/1826442/41038867-f3c05dc6-6997-11e8-960d-5b71a9e812f8.png)
—
Tady by pomohlo odsazeni (jinak to na me pusobi hodne neprehledne)
![image](https://user-images.githubusercontent.com/1826442/41038717-71d99912-6997-11e8-9fed-2732cfee5033.png)
—
Tuto nesouvisi s fontem ale je to peklo jak jsou ty ikonky rozhazeny.
![image](https://user-images.githubusercontent.com/1826442/41038389-3bfe4438-6996-11e8-94ea-322cdf2d3ff9.png)

**Comment by janmichek** [comment]
@jancermak  Caj, ja jsem zasekanej na ZD, tak jen v rychlosti. Ty bily prostory - samozrejme souhlas. TO bylo blbe i pred vymenou fontu. Ted bych to nemichal do tyhle issue. Idealne kdyz na to vytvorime separatni issue, takovejch veci je urcite vic.

Ohlesne tech fontovych veci
- celkove jsem cekal ze to trosku vic rozeberes, mozna jsem se nevyjadril spravne
- talcitko description - tady teda vnimam nekonzistenci. Rekli jsme si ze akcni tlacitka (odkazy na akci) budou GH 700. Proc by tenhle mel bejt jinak. Za me nejidealnejsi by bylo presunout to do pravyho panelu mezi ostatni akce + se da takhle elegantne zbavit 'Rename' z drobeckovy navigace.
Takze navrhuju to nechat takhle jako ostatni akce a vyhledove presunout 'Describe' a 'Rename' do pravyho paelu

- Co se tyce tech Jobu, tak kdybych to udelal jak pises, tak hned v dalsim kroku vidim nekonzistenci.
Seznam Jobu - navrhujes nazev dat nazev komponenty tucne - moje idea byla - nazvy entit nastylovat WH 500
Potom na detailu Jobu by to taky vizualne nesedlo a ani to neni nazev entity to co ukazujes. Respektive je to nazev entity ale ne v danym kontextu (nazev extractoru v Jobs sekci)

**Comment by jancermak** [comment]
1)

2) — description = my mistake — v ten okamzik jsem ho vnimal jako placeholder toho inputu na description a ne jako tlacitko. — souhlasim nechme ho tak s GH.
Co se tyce presunuti editace nazvu a description. Me ta editace nazvu na kliknuti nahore v drobeckovce prijde fajn. Vadi mi nekonzistence u descriptionu - ze tam nejde kliknout na text a tim se zapne editace. Musel bych nakreslit.

3) explodovala mi hlava 🤯— probereme osobne

**Comment by Halama** [comment]
id jsme v seznamu jobu nechteli protoze je k nicemu. kdysi tam bylo a dali jsme ho pryc.

**Comment by janmichek** [comment]
Z tyhle strany tomu rozumim:
Idcko je vetsinou nejaky haluzni cislo co pouzivaj pocitace a uzivateli to nerika zhola nic.

Ja osbne se pomoci idcka v KBCUI orientuju a domnivam se ze to maji podobne data-minded uzivatele.
Takze do jisty miry to slouzi i jako nazev entity. (Zkusime tohle schvalne zitra rozmaznout ve FB komunite)

Zase kdyz v listu jobu to IDcko chybi, tak to taky nepusobi kdovijak nazorne. Na prvni pohled to muze vypadat jako seznam konfiguraci (ne instanci)

Jiny napady nez s navrhovanymi zmenami vyse zatim nemam.

**Comment by janmichek** [comment]
Tady jsme se domluvili ze je nutny udelat odbocku. 2 ruzny fonty v nekonzistentnim UI to jeste vic zneprehledni. 
https://github.com/keboola/kbc-ui/issues/1800

**Comment by ujovlado** [comment]
BTW, nestalo by za to zacat s jednym fontom - Whitney? Na tom by sa mohli odladit rezy a potom len replacnut pozadovane casti za Gotham?

**Comment by janmichek** [comment]
Jo, to mozny je

**Comment by janmichek** [comment]
Zprocessuju to teda

**Comment by ujovlado** [comment]
Ide mi skor len o to nezahodit toto analyzovanie/pracu len preto, ze su tam nejake "nezrovnalosti". Ak sa najprv popreraba "polovica kbc", potom sa budeme musiet k fontom vratit znovu a prejst si to zase. :)

**Comment by ujovlado** [comment]
A tipol by som si, ze skor daladime fonty, nez sa nam podari zjednotit/redesignovat kbc. ;)

**Comment by jancermak** [comment]
@ujovlado  — napad s tim Whitney - je good

**Comment by janmichek** [comment]
Tady uz se jen ceka na merge do produkce.
Aktualni veci jsem prezobal a procistil tady 
https://github.com/keboola/indigo-ui/issues/189
