### ISSUE TITLE
Dummy content before UI load - thoughts (design)

### ISSUE THREAD

**Issue by ujovlado** [keboola/indigo-ui#270]
@jancermak @janmichek 

Co si myslite o niecom takomto? Zobrazovalo by si to kym sa loadne UI. Videl som to napr. pri Slacku, tusim to ma aj Facebook a pod. - je to imho celkom bezne.

![45715774-511a4f00-bb95-11e8-9b49-be7b0336b676](https://user-images.githubusercontent.com/419849/45735360-ec3c1480-bbe7-11e8-95c4-9f4c5c8e3743.png)

**Comment by janmichek** [comment]
Duplicate: https://github.com/keboola/indigo-ui/issues/49

Po technicky strance nevim jestli mame nejaky prostredek co drzi stav nacteni vsech komponent a pak, kdyz je vse ready tak, prepne ze skeletonu na obsah.

Jako rad bych to udelal tuhle fancy novou vec, je to lakavy.
Pripada mi to jako UX tresinka na dortu. Pocitove to zrychli nacitani, ve skutecnosti vsak ne.
Kdyz se podivame kolik mame ruznych loaderu po aplikaci, tak nevim jak to pujde dohromady. Jde mi spis o ten koncept jaky chceme mit?

**Comment by ujovlado** [comment]
Nejde tam ani tak o komponenty, skor tam ide o to, co vidis, kym sa nacita UI (resp. vsetko potrebne pre UI) - proste co tam bude, kym vidis "Loading ...".

Momentalne je tam podpora zo serveru, ktora sa snazi ti pomoct a vyrenderuje ti akysi "skeleton" a vygeneruje ti markup (sidebar, project select, logo, user links, ...), ktory sa potom vymeni za UI. Keby tam tato podpora nebola, vidis len velky napis loading a cakas (ako napr. na devportal-ui).

Problem nastava, ked je sa ten markup lisi - "poskakuje to" ... snazime sa to zjednotit, no uz sa to stalo x krat.

Ale asi s tym este vydrzime - zalozil som to nech vieme, ze je to jedno z rieseni, kym este mame aj server render casti.

**Comment by ujovlado** [comment]
Takze imho to nie je "duplicate of #49", neriesi sa to na urovni komponent. ;)

**Comment by jancermak** [comment]
@ujovlado @janmichek 
dobrej napad — tady posilam navrh vzhledu — (meni se automaticky po 2 sec)
https://invis.io/TMO7T4085C3#/321631018_270_-_Dummy_Loading

PNG zde:
![270 - dummy loading](https://user-images.githubusercontent.com/1826442/45964421-02056b80-c026-11e8-9128-676baeec0f11.png)

**Comment by karimartin** [comment]
Neco ala Slack "empty" data me prijde jako nejlepsi reseni - loader tam pusobi dost divne, u toho region pickeru je to spis jak nejaka chyba skoro.

**Comment by karimartin** [comment]
![LoginLoading](https://user-images.githubusercontent.com/720530/57223507-9a28f180-7006-11e9-8066-0ec4a2a5ec2c.png)

**Comment by ujovlado** [comment]
@karimartin toto myslim ako navrh staci a uz si to dalej prisposobime, super.
