### ISSUE TITLE
Check if yarn link is working

### ISSUE THREAD

**Issue by ujovlado** [keboola/indigo-ui#272]
Since kbc-ui has been heavily updated it is possible that it is not broken anymore.

If it's working, update readme with additional option (yarn link should be preferred)

**Comment by natocTo** [comment]
Včera jak jsem testoval tu Edit komponentu. Tak jsem používal "yarn link" a fungovalo mi to. Tak jen pro info.

**Comment by janmichek** [comment]
Ono to na 95% fungiruje, ale ma to nejaky bugy. Napriklad pri yarn linkovani nefunguje rozbalovani "Show more". Napriklad v modalu IM/OM.
Kdyz se indigo nalinkuje z package tak to prob neni.
Vetsinou jsem to hackoval tak ze jsem zkratka veril svymu kodu a delal to bez monosti vyzkouseni. xD

**Comment by ujovlado** [comment]
To sa mi nezda. Ak to mas dobre linknute, musi to ficat na 100% rovnako - ako keby si to mal z repository.

**Comment by janmichek** [comment]
Mam to linknuty podle navodu. Tobe tohle konkretni funguje?

**Comment by ujovlado** [comment]
Akurat to checkujem, vyzera, ze uz mi to fici. Predtym som to riesil cez `yarn add`, lebo vyzeralo ze webpack 1 mal problem so symlinkami.

**Comment by ujovlado** [comment]
Cez `yarn add` mi to ficalo identicky

**Comment by janmichek** [comment]
Zkusil jsem to jeste jednou prelinkovat ( po updatu yarnu ). ale porad mi to troli.
Nemusime to resit, vim jak to obejit.

Vypis po kliku na 'Show More'
![image](https://user-images.githubusercontent.com/15363559/45814085-ce001280-bcd4-11e8-82a4-92a9de52b9d7.png)

**Comment by ujovlado** [comment]
Hm, divne ... a mas indigo buildnute?

**Comment by ujovlado** [comment]
No vyzera, ze sa to deje len vtedy ked mas v indigo-ui aj node_modules. Nemalo by to ale prekazat. Debugovat to ale zatial nejdem. Ja som to vzdy robil takto:

```
yarn build-lib
yarn rm -rf node_modules
```
^ a to som linkoval.
