### ISSUE TITLE
Region selector on projects index

### ISSUE THREAD

**Issue by Halama** [keboola/indigo-ui#274]
Teď sice vidím region a jejich selector na loginu. Pokud už jsem ale přihlášený tak se rychle přepnout nemůžu ani nevidím v jakém regionu přesně jsem. Myslím že by ten selector mohl být i na seznamu projektů se zvýrazněným aktivním regionem.

![image](https://user-images.githubusercontent.com/903531/45868000-fe9f8500-bd84-11e8-820b-b3089d186fdd.png)

**Comment by janmichek** [comment]
@Halama 
To ano, taky se v tom obcas ztracim. Resilo se to i ve FB komunite - tam byl pozadavek mit to prepinatko nekde v UI projektu (pici ted to nejde nalinkovat).
Da se to dopredu zjistit jaky uzivatel ma projekty v jakym regionu, aby ti to nenabizelo neplatny volby?

**Comment by Halama** [comment]
Ne musí to být hloupý, stejně jako je to na tom loginu. Ty regiony jsou záměrně úplně izolované.

**Comment by Halama** [comment]
v té skupině na FB jsem to četl, teď mě to jenom trklo taky.

**Comment by janmichek** [comment]
Pred loginem je jasny, ze nejde nic poznat.
Dal ( vyber projektu, projekt) uz mi to zas prijde matouci. Predstav si ze celou dobu delas v jednom regionu (tak to asi ma vetsina klientu, ne?) a nabizi ti to nejakou volbu regionu, kterou vubec nepotrebujes. Predpokladam ze je minimum klientu ve vsech 3 regionech.
Chapu oba pripady, nedokazu se ted rozhodnout.

**Comment by janmichek** [comment]
Odkladam si ze kdyby pribyl 4. region, tak uz je efektivnejsi UI koncept Select, ne Radio.

**Comment by Halama** [comment]
Ty regiony jsou úplně izolovaný, takže nic jiného než že je nabídneš neuděláš.

Je pravda že klientů kteří jsou ve více regionech je málo. Jde hlavně asi o CZ maintainery které mají projekty v US i EU.

**Comment by janmichek** [comment]
V tom pripade mi vychazi lip to nedelat. Nebo se da poznat ze uzivatel je maintainer (varianta kdyz uz je user prihlaseny)?

**Comment by Halama** [comment]
jo asi se na to spíš můžem vyprdnout.
