### ISSUE TITLE
list vs tables

### ISSUE THREAD

**Issue by janmichek** [keboola/indigo-ui#28]
vytvorit vzhled + guideline = vygeneruje hodne prace

**Comment by jancermak** [comment]
tuto si tu odlozim:
https://uxdesign.cc/design-better-data-tables-4ecc99d23356
https://ux.stackexchange.com/questions/60715/is-there-a-better-way-than-zebra-stripes
http://www.darkhorseanalytics.com/blog/clear-off-the-table/
https://meta.discourse.org/t/the-death-of-the-grey-no-more-tiger-striping-rows-by-default/28664
https://alistapart.com/article/zebrastripingdoesithelp

**Comment by janmichek** [comment]
tohle je taky super koncept, hodne obecnej. Da se do toho narvat cela aplikace xD https://vimeo.com/album/4261221/video/165624533?utm_source=email&utm_campaign=onboarding&utm_content=12minvid

**Comment by janmichek** [comment]
Pri navrhu tabulky bych pocital s tim ze nad tabulkou jeste muze byt searchbar a neco (tlacitko) co prida novy zaznam do tabulky. V aplikaci se vysytuje i filtrovani hodnot ( to muze byt udelano i nejakym chytrym searchem). Search pro use case 'vim co hledam', razeni a filtrovani pro 'nevim co hledam'.

**Comment by janmichek** [comment]
Navrh k tabulkam - prekladam si to jako apel na koncept shovavani sloupcu, viz koncept vyse
https://www.facebook.com/groups/keboola/permalink/1706333922784172/
![image](https://user-images.githubusercontent.com/15363559/41990855-ec0115d2-7a43-11e8-8d6a-7635839a2bb1.png)

**Comment by janmichek** [comment]
Fixed header concept would be valuable for this https://github.com/keboola/kbc-ui/issues/1719#issuecomment-405865716 because we do not have much space im modal for so many rows  in the table
