### ISSUE TITLE
ConfirmButtons - move here

### ISSUE THREAD

**Issue by ujovlado** [keboola/indigo-ui#296]
Tie buttony su celkom dobry kandidat na presun.

Myslim, ze k tomu nebude treba ani ziadne css

**Comment by ujovlado** [comment]
https://github.com/keboola/kbc-ui/pull/2190

je to ale lowprio

**Comment by ujovlado** [comment]
Treba tam potom pridat `classnames`, teraz to generuje `kbc-buttons undefined`

**Comment by ujovlado** [comment]
@janmichek teraz si robil s ConfirmButtons, imho mozu ist od indiga. Zatial staci ked budu mat funkcionalitu ako v kbc-ui.

**Comment by janmichek** [comment]
PR na vymenu v KBC

**Comment by ujovlado** [comment]
@natocTo vidim, ze si sa vrtal v ConfirmButtons, nedotiahol by si toto?

Je tam uz na to PR ale ten mozeme kludne zahodit a pripravit novy, menili sa tam aj nejake CSS a neviem nakolko je to aktualne https://github.com/keboola/indigo-ui/pull/325

No a potom je tam na kbc-ui, to sa asi bude dat scasti pouzit https://github.com/keboola/kbc-ui/pull/2417 (ked nie, tak tiez nanovo)

**Comment by natocTo** [comment]
Jo mrknu.
