### ISSUE TITLE
Clearable search bar

### ISSUE THREAD

**Issue by ujovlado** [keboola/indigo-ui#300]
Doplnit akciu/ikonku, ktora premaze searchbar

- nieco ako https://components.keboola.com/components
- https://github.com/keboola/developer-portal-ui/blob/0de6f2a4a0725ce66b3ee763e9aee4ce4daff755/src/scripts/common/form/SearchInput.js

Dodatocne info:

- ten "clear" by mal byt button
- po zmazani by to malo focusnut spat do inputu

**Comment by ujovlado** [comment]
Priraduj si tie issues pls, skoro som to zacal dnes robit popri review suvisiaceho PR na kbc-ui.

**Comment by janmichek** [comment]
Aha, ok. Ja jsem myslel zes tu issue vytvoril na zaklade meho podnetu .] myslim ze to mam hotovy, jeste cekam na review. S cim to souvisi?

**Comment by ujovlado** [comment]
https://github.com/keboola/kbc-ui/pull/2219
