### ISSUE TITLE
Modify searchbar to accept query from prop

### ISSUE THREAD

**Issue by ujovlado** [keboola/indigo-ui#304]

**Comment by ujovlado** [comment]
@natocTo chcel by som to doklepnut, rozmyslam o nasledujucej zmene:

- onChange by sa stalo required a drzat query by bolo nutne vzdy mimo komponenty
- query by bola vyhradne tahana z props

Vyhody:

- mohli by sme nastavit query zvonku
- nemiesal by sa tam state/props

Nevyhody:

- BC break

Co si o tom myslis?

**Comment by ujovlado** [comment]
Mam to ready, mozeme to ked tak prejst v PR.

**Comment by natocTo** [comment]
Myslím že to je OK.  Query a onChange je všude v kbc-ui.
