### ISSUE TITLE
UX tuning animations

### ISSUE THREAD

**Issue by janmichek** [keboola/indigo-ui#313]
Mam tady starsi vec, ktera zapadla.

Rad bych dodal UI neco co to odlisi od defaultniho browserovyho / bs stylu.
Myslim si ze malo prace a hodne parady udelaji nasledujici veci. Cvicne jsem to zkousel dodat do browseru a nebylo nutny nic zasadne predelavat, vetsina prace bude na stylech, ktery uz mam vetsinou hotovy.

Neresim ted konkretni styly a animace, s tim si rad pohraju

***Radio a checkbox***
 to mi fungovalo hned v browseru
![tfa](https://user-images.githubusercontent.com/15363559/48487333-30c9e200-e81e-11e8-89cf-6d04cf242b22.gif)
![tfb](https://user-images.githubusercontent.com/15363559/48487334-30c9e200-e81e-11e8-84b0-ffd4ed119aff.gif)

***Loadery***
tim chci vyresit i nekonzistecni, kterou jsem rozkryl tady https://github.com/keboola/indigo-ui/issues/186

Myslim ze se to da obslouzit temato 3 konceptama

**Velky loader** - celostrankovy nebo per komponentu
![loader](https://user-images.githubusercontent.com/15363559/48487440-8b633e00-e81e-11e8-9ee2-9a7f65287c6b.gif)

**Maly loader** - misto spinneru
![tff](https://user-images.githubusercontent.com/15363559/48487412-78506e00-e81e-11e8-85ff-3511feeefd6d.gif)

**Loader button**
![tf1](https://user-images.githubusercontent.com/15363559/48487401-6e2e6f80-e81e-11e8-8c49-fe8428ce776e.gif)

***Animace akcnich tlacitek na hover***
- tady to bude chtit trochu sjednotit
![tfs](https://user-images.githubusercontent.com/15363559/48487516-bea5cd00-e81e-11e8-9666-d522f0353d81.gif)

**Comment by janmichek** [comment]
@ujovlado @natocTo

**Comment by ujovlado** [comment]
Mne sa animacie pacia. Ma to vsak jeden hacik. Co sa KBC tyka, som k tomu skor skepticky. Podla mna chceme viac tlacit na profesionalny/technicky vzhlad. Taketo veci to robia (podla mojho nazoru) len viac hrackarsk (spomen si na AlertBlock, ktory tiez vyzeral povodne ako z cirkusu).

No a v neposlednom rade, animacie by som lestil az vtedy, ked nebudeme mat co robit.

V skratke, ked dam niekde Run, je pre mna 100x dolezitejsie aby ta komponenta zbehla/robila co ma, ako to, ze mi zabublinkuje Run button.

**Comment by janmichek** [comment]
Muj zamer byl, ze jsem do aplikace chtel zacit promitat nejakou personu, coz hranici s brandingem - napr Mailchimp.
Nerikam ze ty animace musi vypadat takhle, klidne to muze byt i neco stridmejsiho, ale osobne mam v aplikaci rad vizualni feedback, ze jsem udelal nejakou interakci.
Nevim jestli jsme si rekli, ze budeme tlacit nejaky konkretni vzhled nebo koncept. Jasne nejdriv veci musi fungovat, pak je muzeme lestit, to je ale v mym scopu jen castecne.

**Comment by ujovlado** [comment]
> Muj zamer byl, ze jsem do aplikace chtel zacit promitat nejakou personu, coz hranici s brandingem - napr Mailchimp.

Jo, chapem. Presne z toho mam pocit, ze sa to stane hrackarske. Po uspesnom jobe na mna zakyva chapadlom chobotnica :)

> Nerikam ze ty animace musi vypadat takhle, klidne to muze byt i neco stridmejsiho, ale osobne mam v aplikaci rad vizualni feedback, ze jsem udelal nejakou interakci.

To myslim mame ... vid. loadery/notifikacie/...

> Nevim jestli jsme si rekli, ze budeme tlacit nejaky konkretni vzhled nebo koncept. Jasne nejdriv veci musi fungovat, pak je muzeme lestit, to je ale v mym scopu jen castecne.

To sme si myslim nepovedali, ale ja mam pocit, ze ideme skor konzervativnejsou cestou. V tvojom scope nie je backend, jasne. ... Ale mozes napr. investovat cas do UX - t.j. napr. zlepsis cast ovladania alebo co ... a to ze to bude mat lepsie UX je vacsia vyhra ako to, ze na konci nejakeho flow mam animovany button alebo skakajucu vevericku.

Ide mi proste o to aby sme na to nesli opacne. Nechcem aby sme pridavali Easter eggs, ked vo vysledku sa produkt bude pouzivat naprd. Chcem aby sme pridavali Easter aggs potom, co mame vyladene vsetko okolo.

Userovi je jedno, ze sa mu to animuje, ked to musi robit na 10 krokov namiesto 3.
