### ISSUE TITLE
Img — do keboola guide (via Hanka)

### ISSUE THREAD

**Issue by jancermak** [keboola/indigo-ui#34]
@janmichek — prikladam celkove PNG + rozrezane na jednotliva schemata — SVG datove vychazi lepsi nez PNG.

[try-kbc-schemata.zip](https://github.com/keboola/indigo-ui/files/1475669/try-kbc-schemata.zip)
![schema kbc](https://user-images.githubusercontent.com/1826442/32850096-826cf4f0-ca31-11e7-91fc-56e138c40c45.png)

**Comment by janmichek** [comment]
Nasazeno https://github.com/keboola/kbc-ui/commit/6e46d8c0310b57343a98f51f08b8f1f1633bbdd0

**Comment by janmichek** [comment]
Dle feedbacku hanky, jeji schema vypada takhle:

![image](https://user-images.githubusercontent.com/15363559/33126357-7df067b0-cf84-11e7-8cbd-eaa3c37e1e48.png)

Domnivam se ze zasek je na fontu Gotham. Ja a Jack ho mame nainstalovany lokalne. Takze svg ho cte. Zrejmne ho neumi precist z importu v prohlizeci a zpropagovat do svg. 

https://assets-cdn.keboola.com/kbc-ui/0.2.9-219-gb621e4f/1b81db27a51cacabad04f22d676e90bd.svg
tady je treba videt <tspan xmlns="http://www.w3.org/2000/svg" x="475.431" y="107">Table</tspan> Domnivam se ze to musis prevest do <path>tak jako to bylo v puvodnim schematu. Nebo z tim mas nejaky zkusenosti?

**Comment by ujovlado** [comment]
Dal by som tam png a je pokoj.

**Comment by jancermak** [comment]
Zkrivkuju pismo v SVG a bude vyreseno.

**Comment by jancermak** [comment]
[outlines-svg.zip](https://github.com/keboola/indigo-ui/files/1495894/outlines-svg.zip)

**Comment by jancermak** [comment]
[schema 0.svg.zip](https://github.com/keboola/indigo-ui/files/1496785/schema.0.svg.zip)
