### ISSUE TITLE
SVGO kompilace pri renderovani

### ISSUE THREAD

**Issue by janmichek** [keboola/indigo-ui#35]
Overit ze to funguje alespon stejne dobre jako SVGOMG (webovy kompresor).
Jenom to jsem davam aby trackoval status.

**Comment by janmichek** [comment]
@ujovlado Tohle vypada jako vyreseny tady https://github.com/keboola/indigo-ui/blob/527aa45fa5ded6b9a69db76ed399d86e2952eb5d/src/svg-react-transformer.config.js#L5 , vid?

**Comment by ujovlado** [comment]
No SVGO sa tam pouziva, neviem ale co bolo cielom tohto issue. Ak len pouzit SVGO tak je to splnene :)

**Comment by janmichek** [comment]
Super, poreseno

**Comment by janmichek** [comment]
Jeste jednou jsem to dukladne testnul pred a po kompilaci ikon. Komprimuje to vyborne

**Comment by ujovlado** [comment]
To som rad, lebo v podstate sme pouzili nejake default nastavenie z `svg-react-transformer` :)
