### ISSUE TITLE
Displaying of nonexistent table

### ISSUE THREAD

**Issue by ujovlado** [keboola/indigo-ui#357]
Je tam toho viac.

## 1. Odkaz na tabulku

- @natocTo to otvoril vramci https://github.com/keboola/kbc-ui/pull/2750
- moznosti su cca taketo: https://github.com/keboola/kbc-ui/pull/2750#issuecomment-457324529, treba to vsak premysliet

## 2. Detail IM pre neexist tabulku

- vlastne len zobrazenie konfiguracie
- v IM transformacii je co cca OK (bez errorov), no tiez to mozeme spravit read only s alertom
- generic table IM sme sa rozhodli fixnut, hadza to errory

## 3. Riadok IM (panel)

- Tu mame stale moznost editacie (fa-pencil), no aj ked tabulka neexistuje -> to by sme mali opravit
- Imho by bolo fajn, mat tam `fa-eye` -> t.j. idem si pozriet detail IM pre neexist tabulku (napr. ak chcem podla toho nastavit novy IM)
- Ak tabulka neexistuje, je zbytocne mat tam size (suvisi to s tym odkazom - bod. 1.)

## Issues

- [x] Generic table IM detail fix -> https://github.com/keboola/kbc-ui/pull/2749
- [x] Transformation table IM detail fix -> https://github.com/keboola/kbc-ui/pull/3259
- [x] IM row - ikonky a size -> https://github.com/keboola/kbc-ui/pull/3260
- [x] Odkaz na neexistující tabulku -> https://github.com/keboola/kbc-ui/pull/3261

**Comment by ujovlado** [comment]
Povedal by som, ze ako prvy set vylepseni ok. Este by som sa k tomu rad vratil, ked budeme riesit redesign.

**Comment by natocTo** [comment]
Prozatím teda můžu zavřít, tady je hotovo 4/4.
