### ISSUE TITLE
otestovat guide mode

### ISSUE THREAD

**Issue by janmichek** [keboola/indigo-ui#36]
Zatim cekej na zadani, jen si to tu odkladam.

- Radi bychom abys to zvalidoval ty osobne po UX strance + zkusit na uzivatelich. 
- Muzem spolu vymyslet scenar pro user tesy
- ukazu ti zapout a resetovat lekce

**Comment by janmichek** [comment]
Skvele, tak mame pripraven Guide Mode k testum.

- prosim zvaliduj Guide Mode za Jacka / UX veci. Tady je todo kam piseme issues (interni kolecko) https://github.com/keboola/kbc-ui/issues/1349

- potom bych te poprosil at zkusis user testovani.
Jak to zprovoznit - 
1. Pokud ho nemas zaply tak v Settings & Users -> Settings
2. Idealne kdyz si vytvoris v Connection cisty projekt - mas na to opravneni?
3. Potom mozna bude potreba vymazat Local Storage (kvuli odemykani lekci). V Chrome se to dela -> F12 -> Application -> Local Storage -> http://connection... -> oznacim 'kbc-ui-guide-mode' a smazu -> reload stranky.

Pokud je testovani dokonceno, a chces na to pustit dalsiho usera, je potreba opakovat bod 2 a 3.
Pokud chces testovat vic uzivatelu najednou, kazdy bude potrebovat svuj novy projekt, jinak se jim tam budou plest data od jinych uzivatelu.

- chces pomoct s vymyslenim scenaru?

**Comment by janmichek** [comment]
@jancermak Napis mi sem potom prosim nejaky zakladni udaje kdy/kde chces udelat uzivatelske testovani.

**Comment by Halama** [comment]
S tim uzivatelskym testem bych to nejak moc nehrotil, ukazal par lidem, zpracoval pripadne pripominky a sup s tim do produkce kde se to otestuje nejlip.

**Comment by jancermak** [comment]
Moje komenty vse v invissionu — https://invis.io/27EXDXLMN#/268969793_KBC_-_Guide_Mode_Review_1 , Jan je tam pridanej.

**Comment by janmichek** [comment]
Znovu oteviram, jenom pro poradek, kdyz se Jack nemel k user testum. Mam 3 subjekty, poznatky byly celkem jednoznacny, svuj ucel to splnilo. Bud se mi zitra v coworkingu podari sehnat nejaky data-minded subjekty, kdyz ne, uz to nebudu hrotit. https://docs.google.com/document/d/15MBC6seI6Rod5hkByoklI8RffX7Fvn5Rx6Tz8RHQFok/edit
