### ISSUE TITLE
Replace Whitney font by Roboto

### ISSUE THREAD

**Issue by ujovlado** [keboola/indigo-ui#370]
Mozno si to bude vyzadovat viac uprav ako len font-family, pretoze whitney tam malo ine rezy.

**Comment by ujovlado** [comment]
Whitney tam malo:

- 400 normal
- 600 semi bold

**Comment by ujovlado** [comment]
V tom navrhu od Kariho sa pouziva 400 a 500, tak asi mozeme aj tu.

**Comment by natocTo** [comment]
Říkám si zda tam nekonec nepřihodit 300, když vidím na kolik místech v Indigo-ui to je použito. Našlo mi to 11 výskutů v 9 souborech. Kde dvakrát jde o variable, takže ta taky může být někde použita.

Font-weight: 500 tam je 11 krát v 5 souborech, ale to bych klidně upravil třeba na těch 600 to si myslím bude ok.
