### ISSUE TITLE
Check if outer-pages.less can be removed

### ISSUE THREAD

**Issue by ujovlado** [keboola/indigo-ui#393]
Related: #391 

- [x] `.kbc-outer-page` https://github.com/search?q=org%3Akeboola+kbc-outer-page&type=Code .. uz le try-keboola-com, co nie je issue.
- [x] `.kbc-error-page` https://github.com/search?q=org%3Akeboola+kbc-error-page&type=Code
- [x] `.kbc-projects-list` https://github.com/search?q=org%3Akeboola+kbc-projects-list&type=Code
- [x] `.dropdown-header` duplicita https://github.com/keboola/indigo-ui/blob/4c7621bc8bf02bc37e756ad96db03a1f7e0d0262/src/indigo/less/sidebar.less#L79

**Comment by natocTo** [comment]
Jak jsme psal tak `.kbc-outer-page` není v KBC-UI nikde.
Tak pokud to není na connection někde, tak se celá ta sekce může také vyhodit.

**Comment by natocTo** [comment]
`kbc-error-page` také v KBC-UI nedohledám, tak asi nemáme

**Comment by natocTo** [comment]
To samé platí pro `kbc-projects-list`.

**Comment by natocTo** [comment]
Pak už tam zbude jen jedna věc `dropdown-header`, která je použita v ProjectSelect (staré UI), to pak půjde asi vyhodit až budeme mít menu nahoře. Tam to pak musím stylovat znovu tak či tak.

**Comment by ujovlado** [comment]
Projects-list tam este stale je myslim: https://github.com/search?q=org%3Akeboola+kbc-projects-list&type=Code

**Comment by ujovlado** [comment]
^ ale to este kuknem, nejako sa mi to nezda.

**Comment by ujovlado** [comment]
jo, tak tam je to ID ;) ... super

**Comment by ujovlado** [comment]
Asi aj ten dropdown-header:

https://github.com/keboola/indigo-ui/blob/4c7621bc8bf02bc37e756ad96db03a1f7e0d0262/src/indigo/less/sidebar.less#L79

**Comment by ujovlado** [comment]
Takze si sa nakoniec trafil :)
