### ISSUE TITLE
Publish to npm

### ISSUE THREAD

**Issue by janmichek** [keboola/indigo-ui#4]
rozbehat build process aby sa mohlo indigo UI publishnut do npm a ostatne projekty si ho mohli loadnut

**Comment by ujovlado** [comment]
Na toto by som sa tiez kukol. Aby sme to nemusel loadovat takto:
https://github.com/keboola/kbc-ui/blob/96f9d43/package.json#L38

**Comment by ujovlado** [comment]
Ak to pojde, publishol by som to ako `@keboola/indigo-ui`. Potom by malo ficat `yar add @keboola/indigo-ui`

**Comment by janmichek** [comment]
@ujovlado Uz jsi nekdy publishoval na npm? JA to tady zkousim a nedari se. Pakmanager moc nefrci, chybova hlaska k nicemu xD Tak mi jde o to jestli na to mam prichazet nebo uz vis jak na to. Ja bych to rad propojil

**Comment by ujovlado** [comment]
Done: https://www.npmjs.com/package/@keboola/indigo-ui
... je to prva publishnuta verzie, este to bude chciet doladit

**Comment by ujovlado** [comment]
https://github.com/keboola/indigo-ui/releases/tag/v0.1.1
