### ISSUE TITLE
 Only component CSS (v12)

### ISSUE THREAD

**Issue by natocTo** [keboola/indigo-ui#402]

**Comment by natocTo** [comment]
Tak na tomto se asi může začít.

- chceme teda vyhodit custom ikonky
- chceme vyhodit styly co nepatří přímo k nějaké komponentě
- navrhoval bych vyhodit i komponenty co nejsou "naše" - třeba přehled `bootstrapu`, to si myslím že tu nemusí být, ani nemusí styl sedět když budu mít v KBC-UI nějaké custom styly kvůli grafice
- asi teda vyhodit i věci kolem úpravy bootstrapu jen třídou - třeba `Popover` tam má story, jen protože tam je třída popover-wide nebo `Tabs` tam mají story asi jen na ukázku, nevidím žádnou custom třídu

Jak to bude s obrázky typu `admin-404-bg`

**Comment by natocTo** [comment]
- bootstrap tam vlastně asi má smysl když ho "konfiguruji" v indigu, jako základ - barvy, font apod

**Comment by natocTo** [comment]
- Jak to ještě bude s "moduly" typu - `kbc-admin-module` nebo `kbc-admin-project-overview`?
- ještě tam vidím modul `legacy` ten asi mohl jít pryč už ve verzi 10, to vypadá jako něco starého

**Comment by natocTo** [comment]
Odlažím si odkaz na font-awesome https://fontawesome.com/how-to-use/on-the-web/setup/using-package-managers
Tam bude potřeba udělat ty kroky kolem PRO verze si teda.

**Comment by ujovlado** [comment]
Ten stary ikon font pojde prec, to ano. (Mozno by sme ho uz mohli vyhodit z kbc-ui aj skor). Treba ale porozmyslat, ako sa budu tie ikonky pozivat. Ci ako React komponenty alebo len cez CSS, pripadne ci nie nejako inak.

**Comment by ujovlado** [comment]
^ Tie ostatne veci este prejdem :)
