### ISSUE TITLE
Remove custom icon font

### ISSUE THREAD

**Issue by ujovlado** [keboola/indigo-ui#405]
Identifikoval som tieto pouzitia v kbc-ui

```
14 kbc-icon-arrow-right
   1 kbc-icon-cog
   1 kbc-icon-cross
  38 kbc-icon-cup
   4 kbc-icon-keboola-logo
  23 kbc-icon-pencil
   4 kbc-icon-picker
  33 kbc-icon-plus
   1 kbc-icon-storage
```
^ vsetko by sme mali nahradit za font-awestome (zatial v4)

**Comment by ujovlado** [comment]
Rozdelil by som to na 3 PRs v kbc-ui:

```
14 kbc-icon-arrow-right
23 kbc-icon-pencil
1 kbc-icon-cog
```

```
38 kbc-icon-cup
 1 kbc-icon-cross
4 kbc-icon-keboola-logo
```

```
33 kbc-icon-plus
4 kbc-icon-picker
1 kbc-icon-storage
```

logo myslim pouzivame ako svg, no bude to chciet overit.

Po tomto to mozeme vyhodit z indigo-ui myslim.

**Comment by natocTo** [comment]
Koukám že ještě je nějaké použití přímo tu v Indigu - `InlineEditInput` a `RefreshIcon`. Tak ještě to nahradím tu. Možná budu muset nalinkovat Font Awesome asi co.

**Comment by natocTo** [comment]
Všechny části mergnuté tak toto zavírám.
