### ISSUE TITLE
Remove custom react components icons (as react components)

### ISSUE THREAD

**Issue by ujovlado** [keboola/indigo-ui#406]
Toto sa nestihlo nastastie daleko dostat a tych ikon pouzivame len par.

**Comment by ujovlado** [comment]
Budu tu 2 casti:

- vyhodit `{ Icon } from '@keboola/indigo-ui';`
- a podobna vec tu -> t.j. indigo-ui nebude pouzivat tie svgcka.

**Comment by ujovlado** [comment]
Na indigo-ui toho bude trosku viac, no nemal by s tym byt problem. Bude treba upravit malicko aj css.

**Comment by ujovlado** [comment]
A bude to BC break, takze este stihneme v11 asi skor :)

**Comment by natocTo** [comment]
Mrknu ještě dnes.

**Comment by ujovlado** [comment]
Myslim, ze to budu len upravy SearchBar a AlertBlock.
