### ISSUE TITLE
Base CSS (v12)

### ISSUE THREAD

**Issue by ujovlado** [keboola/indigo-ui#411]
Mal by tu byt zaklad, ktory sa bude dat dalej pouzit:

- v indigo-ui-kbc (co budu vlastne styly, ktore bude pouzivat len backendova cast connection)
- kbc-ui

Na zaciatku to bude default bootstrap. Potom pribudnu dalsie styles ako napr. pre buttony, modaly a pod.

V tejto faze by tiez bolo fajn pripravit si nejake helper classes a pod.

**Comment by ujovlado** [comment]
Tymi helpermi som myslel nieco ako https://getbootstrap.com/docs/4.3/utilities/spacing/ (niekde najdes na to issue, uz to tu raz bolo) a pod. aby sa to dalo dalej len "classovat" a skladat.

**Comment by natocTo** [comment]
Helpery si asi nechám na kbc-ui, budu je používat tam tak to bude lepší tam. Když usoudím že se bude hodit nový helper tak to bude jednoduší než opět přes indigo.

**Comment by natocTo** [comment]
Jsem myslel že to `indigo-ui-kbc` bude používat právě třeba tu verze v11 abych to tu mohl celé promazat nebo to tak není?

Jsem myslel že v12 bude čístý bootstrap + css ke komponentám co tu mám + případně drobnosti jako varianta buttonu "link-inline" apod. Ale že jinak tu nebude nic navíc.
