### ISSUE TITLE
Bootstrap showcase subpage

### ISSUE THREAD

**Issue by janmichek** [keboola/indigo-ui#44]
vytvorit stranku vsech BS komponent k snadnejsi vidimaci

**Comment by ujovlado** [comment]
@janmichek Priradil som ti zatial toto. Myslim, ze by sme to mali spravit ako prve (a potom updatovat), aby sa kedykolvek dalo kuknut, ako vlastne bude vyzerat, ked sa pouziju v nejakej komponente defaultne bootstrap classy (kedze z bootstrapu vychadzame). A tiez asi zistime, kde je nieco pokazene (pridane styles ku classam, kde nemali byt a pod.).

Asi by to mohol byt markup vybraty z https://getbootstrap.com/docs/3.3/. Urcite to tam nemusime dat cele, staci myslim zakladne pouzitie - resp. co uznas z vhodne (idealne tak aby to pokryvalo, co najviac toho, ako to pouzivame v `kbc-ui`.

V ramci tohto by sa nemali menit ziadne CSSka a malo by ist len o pridavanie do storybooku.

Kludne to rozdel na viac PRs.

**Comment by janmichek** [comment]
Fajn, jdu na to mrknout.

**Comment by janmichek** [comment]
@ujovlado Domnivam se ze lepsi bude pouzit komponentovy markup ala react-bootstrap. Cvicne jsem prekopiroval staticky html markup z odkazu cos posilal a ty skripty tam nefungujou - dropdown, modal, ...

**Comment by ujovlado** [comment]
Jo, na veci ovladane javascriptom ano, na zvysok je to imho jedno - a malo by to fungovat rovnako. Asi by som ale uprednostnil standardny markup pred tym react-bootstrapovskym. (t.j. zda sa mi lepsie pouzit `<button className="btn btn-primary">aa</button>` pred `<Button bsStyle="primary">aa</Button>`).

Ale to je asi len o tom ako som zvyknuty - napr. na devportal som sa snazil pouzivat co najviac standardneho html, aby som nemusel pridavat dalsie zavislosti.

**Comment by ujovlado** [comment]
Pridam teda do `v2.1` zavislost na `react-bootstrap`

**Comment by ujovlado** [comment]
Ta zavislost uz je v mastri, takze to kluden pouzi. Tym padom to asi mozeme rozdelit aj na 2 stories. Jedna bude `Bootstrap` a druha `React Bootstrap`, kde v tej druhej budu komponenty, co potrebuju nejaku interakciu.

**Comment by janmichek** [comment]
Dobre, dik za pripravu. JEste na tom budu pracovat. Zatim jsem vykopirovaval podle toho, ktere komponenty jsou pouzite. Zitra se to chystam projet podrobneji.

**Comment by janmichek** [comment]
Ohledne tech 2 stranek - myslim ze by mohlo stacit jen ta React Bootstrap. Snadneji se mi to pise jak je to obaleny v komponentach a je tam i mensi prostor pro chyby.  Kod si pripadne vykopiruju na jinych podstrankach. Nebo jakou vyhodu myslis ze by mela 'Bootstrap' stranka navic?

**Comment by ujovlado** [comment]
No myslel som to takto:
- Bootstrap - obyc. komponenty, ktore vlastne nepotrebuju JS (button, table, form, ...)
- React Bootstrap - tie co potrebuju JS (modal, tooltip, ...)

Ma to taku vyhodu, ze mozem pouzit cisty HTML markup - co sa moze hodit napr. v connection, kde mame niektore stranky "server render".

Ale asi je to fuk ... pokial tam ta moznost pouzit klasicke bootstrap classy ostatne, nemusi to byt v examploch (my o tom vieme).

Dalsia alternativa je, ukazat to tam dvojmo. T.j. napr. pre button by si tam ukazal obidva sposoby.

**Comment by janmichek** [comment]
@ujovlado myslim ze to mam, mrkni, pripadne komentuj https://github.com/keboola/indigo-ui/pull/61
