### ISSUE TITLE
Celostrankovy modal - detailu tabulky

### ISSUE THREAD

**Issue by janmichek** [keboola/indigo-ui#46]
Tady bohuzel budu prudit xD imho jsou modaly v kbc pouzity spatne. Modal ma slouzit na rozhodnuti kriticky a nevratny operace 'Overwrite? -> Yes/No'. 
Je to neco co te ma vyrusit z bezny flow, proto to okno nad aplikaci.

Potom vznikaji prave takovy pozadavky jako 'fullscreen modal'. Je mi jasny ze to nepujde jen tak z aplikace odstranit, musime postupne. Ale momentalne bych alespon ten antipattern neprizivoval. Pokud ta vec pujde udelat na podstranku, prosim udelejme to.

**Comment by kacurez** [comment]
Table preview je cez featuru urobena na podstranku(tj ma vlastnu url) ale zobrazuje sa ako staticky modal roztiahnuty na celu stranku
kod je tu: https://github.com/keboola/kbc-ui/blob/master/src/scripts/modules/table-browser/react/Index.jsx
Je to teda na user featuru `ui-devel-preview`. Ak user featuru nema tak sa zobrazi klasicky modal cez komponentu:
https://github.com/keboola/kbc-ui/blob/master/src/scripts/modules/components/react/components/StorageApiTableLinkEx.jsx


Nejake zadanie je popisane tu: https://github.com/keboola/connection/issues/995

**Comment by kacurez** [comment]
to zadanie(https://github.com/keboola/connection/issues/995) je vlastne len "kick-off" table preview na vlastnu stranku ale samotny obsah sa tam neriesi. To sa este doplni, neviem otom zeby k tomu bol nejaky navrh. Moze sa minimalne zacat z toho co tam je teraz.
