### ISSUE TITLE
Deploy dist to S3

### ISSUE THREAD

**Issue by janmichek** [keboola/indigo-ui#5]
spravit deploy css do cloudfornt (aby sa to mohlo loadnut v connection zatial kvoli BC)

**Comment by ujovlado** [comment]
- Cielom tohto je nahradit kbc-boostrap
- Ten build process teda moze byt pre zaciatok rovnaky (skopirovany a skontrolovany, ci fici ako ma, lebo tu som uz pouzil novu verziu gruntu a suvisicich libs)
- Vysledkom by malo byt CSS, ktore bude 1:1 s aktualnym kbc-bootstrap

**Comment by janmichek** [comment]
Ok, dobre udelejme to tedy at se to loaduje z CDNka. Rad bych to teda nejak nastavil, ale nevim co mam pro to udelat. NEvidim nikde prihlasovaci udaje do Cloudfront

**Comment by janmichek** [comment]
Caj, mohli bychom propojit toto? Tusim, ze se mi to bude brzo hodit .) diky

**Comment by ujovlado** [comment]
k tomuto sa uz tento tyzden nedostanem ...

rozmyslal som ale nad tym a spravil by som este male zmeny:
- deploy do s3 by sa robil vzdy po pushni do mastra
- do cloudfront by sli len tagy (neskor by menili aj verziu v connection)

^ dam vediet do tohto issue

**Comment by janmichek** [comment]
@ujovlado Zdarek, muzem rozchodit ten deploy? Muzu pro to neco udelat?

**Comment by ujovlado** [comment]
@janmichek No ak chces, kludne sa do toho toho pusti, tak ako som pisal vyssie https://github.com/keboola/indigo-ui/issues/5#issuecomment-315755448. Prihlasovacie udaje na cloudfront nepotrebujes, to setupneme neskor (bude to len proxy nad s3).

Skus napr. pripravit Grunt task, tak ako je tu:
https://github.com/keboola/kbc-bootstrap/blob/6510d35/.travis.yml#L8

To je task, ktory sa pouzije na zbuildovanie tych CSS, tak aby sme ich mohli potom deploynut.

Staci ak spravis PR, kde do Travis configu, do sekcie script pribudnu dva commandy:
- `grunt build prepare-revision` (toto aktualne treba skopcit z Gruntfile a doladit)
- command,  ktory vyslistuje, co sa zbuildovalo

**Comment by ujovlado** [comment]
@janmichek alebo ak mas nieco ine, pockaj, ja sa myslim k tomu dostanem zajtra/pozajtra

**Comment by janmichek** [comment]
dik, mrknu se na to a dam vedet kam jsem to posunul

**Comment by janmichek** [comment]
Jeste to teda nefunguje xD ale pripravil jsem to zde https://github.com/keboola/indigo-ui/pull/16

**Comment by janmichek** [comment]
@ujovlado jako vypada to ze to neco dela. Ale nevim jak overim, ze to opravdu funkuje

**Comment by ujovlado** [comment]
ok, mam to zrovnane, v branchi `kbc-bootstrap` pripravim deploy a ak to bude rovnake, potom to otagujem

![screenshot_2017-08-09_16-05-55](https://user-images.githubusercontent.com/419849/29125667-a66171e0-7d1c-11e7-9759-8717178f7c85.png)

**Comment by ujovlado** [comment]
> @ujovlado jako vypada to ze to neco dela. Ale nevim jak overim, ze to opravdu funkuje

Ked na to tak pozeram, nemohlo to fungovat ani zdaleka ... skapalo ti to predsa hned na tom, ze neexistuje ten grunt task.

**Comment by ujovlado** [comment]
Fixed in #17
