### ISSUE TITLE
Fix V1 styles

### ISSUE THREAD

**Issue by janmichek** [keboola/indigo-ui#60]
Ve V1 se neaplikuji styly, ktere tam byli puvodne nalinkovane. Zatim jsem nezjistoval, jenom odkladam.

https://indigo.keboola.com/v1

**Comment by janmichek** [comment]
Psal jsi ze na to mrknes, tak jenom pripominam .] Ty styly tam evidentne porad chybi

**Comment by ujovlado** [comment]
Toto uz nebudem riesit, je to imho zbytocna praca, kedze mame v2. Branch tam je, aj jej kod, je oznacena ako protected. Cokolvek budeme chciet odtial vziat, mozeme.

**Comment by janmichek** [comment]
Skoda, mel jsem tam zasuplikovano spoustu prace, drobnych vylepseni do KBC. Vetsinou se zakladaly na stylech. Tim ze nejsou videt tak jsou zahozeny. Ocekaval jsem alespon nejakou diskuzi, nez to zavres

**Comment by ujovlado** [comment]
Ved kludne sa o tom bavme. Je tam branch v1, kde by to malo vsetko byt. Vies si to checkoutnut a povedat co tam chyba?

Nemam pocit, ze by som to zmazal alebo tak. Mozno je to len zle deploynute.

**Comment by janmichek** [comment]
Podivam se na to,, zkusim fixnout.

**Comment by janmichek** [comment]
Zatim jsem na to neprisel

Podle vseho by to melo vybuildit ten uncompressed styl.
Vypada to ze build pro V1 se spusti pushem do V1 vetve, ale oproti lokalni instanci tam chyby styly z indigo-storybook.less
https://travis-ci.org/keboola/indigo-ui/jobs/352180943

**Comment by janmichek** [comment]
@ujovlado potrebuju vysvetlit jak, v jakym poradi funguje ten build process. Pripada mi ze se stane to samy na lokalu i na serveru, nicmene ty styly pak nevidim deploynuty.

**Comment by ujovlado** [comment]
skusim ti to deploynut este raz manualne

**Comment by ujovlado** [comment]
Fixed in https://github.com/keboola/indigo-ui/commit/97084a6eb7fe27e4affa3d92b63f88e3575d07f3

**Comment by ujovlado** [comment]
Prosim, uz ziadne zmeny v tej `v1` ... je to z mojho pohladu deprecated a nechcem tomu venovat cas a udrziavat to. (mazat to samozrejme nejdem, nech sa da odtial pripadne "vyzobavat", co je uzitocne)

**Comment by janmichek** [comment]
Eeej bomba! 
Jasna vec, pridelavat nic nehodlam, jenom linkovat stavajici, pripadne presouvat do masteru. Postupne to planuju odstranit
