### ISSUE TITLE
Idea: Split to 2 (or 3) packages (within this repo)

### ISSUE THREAD

**Issue by ujovlado** [keboola/indigo-ui#68]
We can split the code to 2 parts/packages. For example using `lerna`.

1. indigo-ui library itself (what is published to npm) + storybook
2. part for building dist css (what is registered to connection) ... this will include 1.

or to 3 packages, where storybook can be also in separate part (will also include 1., of course w/o storybook)

Idea behind this is to make it more stable (e.g. to have an option release new indigo-ui version without publishing CSS to connection).

**Comment by ujovlado** [comment]
For now, it'll be enough to extract part which is generating/registering css to KBC.

Here's the repo: https://github.com/keboola/indigo-ui-kbc

**Comment by pivnicek** [comment]
I like the 3 packages version :-)

**Comment by ujovlado** [comment]
Toto postuchnem viac, sere ma, ze pridanim novej komponenty (co je vlastne cisty javascrit) sa releasuju/reguju csska do Connection.

**Comment by ujovlado** [comment]
Chvilku som sa vrtal v tom `indigo-ui-kbc`, kde som chcel odfajcit zbytocne veci, no stale sa mi to moc nepozdava - pre lokalne otestovanie by sa zhorsilo developer experience ... a tak idem asi vyskusat tu lernu.

**Comment by janmichek** [comment]
jj koukal jsem ze tam neco kutis, zatim ti asi moc neporadim. Kdybys potreboval neco testnout, dej vedet .]

**Comment by ujovlado** [comment]
Tak som sa bavil s `lerna`, vyzera to dobre, este by som to nechal chvilku ulezat a potom by som to rozbil na samostatne packages. Zacal by som storybookom.

To repo `indigo-ui-kbc` zmazem, nebude to uz treba

**Comment by ujovlado** [comment]
Tak predsalen som to prehodil :) nakoniec sa to pouzuje cisto na deployment, takze to nic neovplyvni.

**Comment by ujovlado** [comment]
Toto tu zavrem, tym, ze vzniklo to separatne repo, releasov tu sa uz az tak nebudeme musiet bat a trosku sa to uvolni - t.j. posraty release indigo-ui nerozbije connection pokial sa nespravi deploy indigo-ui-kbc.
