### ISSUE TITLE
Add prettier

### ISSUE THREAD

**Issue by ujovlado** [keboola/indigo-ui#81]

**Comment by natocTo** [comment]
@ujovlado aktuální? Podíval bych se na to. 
Asi by bylo i lepší to zkusit nastavit a používat nejdříve tu než v kbc-ui.

**Comment by ujovlado** [comment]
@natocTo ano, je to aktualne :) zmysel to ale ma asi len na komponenty. Alebo aj na stories?

Kludne sa do toho pust ;)

Co config? Mas nejaky overeny? Kukni ked tak aky som pouzil na devportal-ui. Idealne keby sme sa dohodli a pouzival rovnaky na vsetkych UIckach.

A chces to zavesit rovno na eslint? Alebo pre-commit hook a lint-staged?

Kludne to tu viac rozpis, zaujima ma to

**Comment by natocTo** [comment]
> zmysel to ale ma asi len na komponenty. Alebo aj na stories?

Zkusil bych jak moc by se lišilo použití na vše nebo na komponenty, ty jsou určo důležitější.

> Co config? Mas nejaky overeny? Kukni ked tak aky som pouzil na devportal-ui. Idealne keby sme sa dohodli a pouzival rovnaky na vsetkych UIckach.

Bohužel nemám. Koukám na developer-ui a je ta samotný prettier, myslím že by už stálo za to využít společně s Eslint.

> A chces to zavesit rovno na eslint? Alebo pre-commit hook a lint-staged?

Určitě bych rád použil také eslint. I bych více stavěl na eslintu, respektive bych spíše hledal ideální Eslint config, z kterého by vycházel i Prettier. Otázka jaký zvolit, super populářní je AirBnb ale je hodně striktní, určo by šel použít i tak, jen nějaké pravidla upravit. Nebo si dát práci a snažit se upravit všechny tipy.
S pre-commit, lint-staged nemám zkušenosti. Ale to asi může být dyštak další krok pokud budeme mít základ hotový.

Zkusím začít tím Eslint AirBbb + Prettier a kouknu kolik problému a warningů to vyvolá, když to bude moc napíšu nebo zkusím vybrat jiný konfig. Je určo možný psát vlastní pravidla jako na KBC-UI ale preferoval bych spíše využít jiný ověřený (hlídaný, opečovávaný) a případně poupravit pár pravidel.

**Comment by natocTo** [comment]
Jinak můžu použít také config z developer-portal-ui. Ať to tu je stejné tyto pravidla.

**Comment by ujovlado** [comment]
Parada ... tam sa este oplati kuknut, ci tam uz nejaky eslint config nie je. Mna sa prave zda, ze tym, ze je to postavene na podobnom principe ako je "create-react-app", tak by tam uz nieco mohlo byt

**Comment by ujovlado** [comment]
Napr. na devportal-ui mame len prettier, eslint je v tom stacku (create-react-app resp. react-scripts) by default.

**Comment by natocTo** [comment]
Tak myslím že ten AirBnb by mohl být. Vypnul jsem na začátku 5 pravidel a ukazuje mi to okolo 50 věcí kde většina jde upravit automaticky.
Pouštím teda pouze na .jsx soubory. Koukám že ikonky v indigo/components/ jsou s .js příponou. Což by se mohlo jen upravit na generování jsx.

**Comment by ujovlado** [comment]
Skor asi skoncime na `.js`, nie na `.jsx`, poslem PR, nech je to jednotne

**Comment by ujovlado** [comment]
Urcite by som sa ale nepustal do vytvarania nejakeho vlastneho eslint configu - treba pouzit nieco strandardne, hotove.

**Comment by natocTo** [comment]
Určitě. Čtu si toto https://alligator.io/react/linting-react/
kde píšou že Eslint je integrovaný, ale nelze použít s Prettierem. A je težké to konfigurovat apod. Myslím že vlastní eslint bude lepší varianta.

Config souhlasím. Právě proto zkouším asi nejpopulářnější od [AirBnb ](https://www.npmjs.com/package/eslint-config-airbnb). Na to připojím ty 4 pravidla Prettierů co jsou v developer-portal-ui ať je to jednotné.

**Comment by ujovlado** [comment]
Ok, ved uvidis ;) Ja som to tam nejaho hackoval, aby tam vobec nejaky linter bol - kukni `webpack.config.js`

**Comment by natocTo** [comment]
@ujovlado tak to jde docela dobře, samo s tím že na začátku asi vypnu více eslint pravidel a poté případně proberem které znovu zapnout a dodělat.

Mám poslední "větší" problém s jednou ikonou. Koukám že třeba ikonu arrow-down.svg ti to převede hezky na ArrowDown.js. Nicméně je tam jedna ikona kde je číslo: transformation-2.svg a ta je převedene na Transformation_2.js, kdě mě to pak řve, že mám používat camelcase. Říkám si zda by to nešlo přejmenovat na něco konkrétnějšího (už tam je třeba transformation-overview).

**Comment by ujovlado** [comment]
Este je celkom popularny aj https://standardjs.com (https://github.com/standard/eslint-config-standard), ked tak vyskusaj.

**Comment by ujovlado** [comment]
Na tu ikonku sa pozriem.

**Comment by natocTo** [comment]
Na config-standart jsem také koukal. Zvolil jsem AirBnb pro první pokus protože to mají už více spojené s vývojem v Reactu.
Mám to skoro rozjeté, těch vypnutých pravidel ja nakonec více, ale to není problém pak upravit a dořešit nové eslint problémy. 
Poslední na čem stojím je ta jedna ikonka. Pak to asi pošlu na zkouknutí. Respektive ještě musím otestovat zda to najede apod.

**Comment by ujovlado** [comment]
Ikonka fixed ;)
