### ISSUE TITLE
Refactor/Unify and provide sane defaults for Tabs/Tab

### ISSUE THREAD

**Issue by ujovlado** [keboola/indigo-ui#84]
There are many fixes and workarounds for tabs. We should get rid of them and provide stable solution. Probably by new class (some wrapper, etc.).

1. This is adding padding:

https://github.com/keboola/kbc-ui/blob/3f1d5f9dd3a041d1515aeaa0541aa50131a2c0de/src/styles/app.less#L359-L361

2. This is adding margin (check oauth modal):

https://github.com/keboola/kbc-ui/blob/3f1d5f9dd3a041d1515aeaa0541aa50131a2c0de/src/styles/app.less#L340-L347

3. And this is stylying `*`, which is WTF for me:

https://github.com/keboola/indigo-ui/blob/b454a759bfd8fb8a668b0d92f8e8e98986ad1d80/src/indigo/less/navs.less#L25-L28

**Comment by ujovlado** [comment]
@janmichek napada ta ako z tohto von? :)

**Comment by ujovlado** [comment]
Osobne som za 1., a potom:

- mozeme vyhodit 2. (ale dat nejaku nahradu, lebo 1. nefunguje v modale)
- pridat nejaku wrapper class, ktora mi umozni prida padding na content, ktory je v tabe (teraz to simulujeme pouzitim class `kbc-inner-content-padding-fix`)
- potom vyhodit 3.

**Comment by ujovlado** [comment]
Ak pouzijeme nejaky wrapper, treba dat pozor na tabulky, ktore mame momentalne full size (vid. `navs.less`, kde sa to resetuje.

**Comment by ujovlado** [comment]
A potom sa budeme musiet zbavit aj tejto zveriny:
https://github.com/keboola/indigo-ui/blob/b454a759bfd8fb8a668b0d92f8e8e98986ad1d80/src/indigo/less/navs.less#L20-L22

**Comment by janmichek** [comment]
prozkoumam to a odpovim

**Comment by janmichek** [comment]
No to je radost teda xD dobrej ulovek.

Predpokladam ze jde o sjednoceni v ramci cely aplikace.

Jak bych postupoval:

- nejdriv bych vyzobal odkazy na podstranky kde se Tabs vyskytuji. Pripadne i screenshoty.
- vytvoril demo/prototyp v indigo-ui jak ma vypada sjednocena komponenta.
- prozkoumal jak se tabs soucasne pouzivaji, co se vse vevnitr tabu muze objevit. Nebo naopak uvnitr ceho se muzou tabs objevit.
- potom bych zkusil vyhodit vsechny custom classy ktery ovlivnuji vzhled samotnych tabs
- zacal bych hledat reseni, klidne muzu zacit navrhem co pises. Ted nedokazu posoudit co bude lepsi reseni
- v pripade ze nekde ma custom classa svuj smysl, tak to sikovne pojmenovat a kodifikovat
- vsude asi nebude mozny pouzit jsx markup, neco bude potreba udelat rucne

**Comment by janmichek** [comment]
Castecna pricina problemu je myslim ze developeri si mysli ze se styl izoluje tim ze je ve stylesheetu per komponentu. Coz tak samozrejme takhle nefunguje, jenom pisu jak si myslim ze to vzniklo.

**Comment by janmichek** [comment]
Mam to zacit prozkoumavat?

**Comment by ujovlado** [comment]
No este je aj 4. pouzitie :-D, kde sa to naopak resetuje:

https://github.com/keboola/kbc-ui/blob/3f1d5f9dd3a041d1515aeaa0541aa50131a2c0de/src/styles/app.less#L363-L365

**Comment by ujovlado** [comment]
Jasne, kludne to zacni preskumavat, zbavime sa aspon tych custom veci, ktore to lenn komplikuju.

Este by bolo fajn mat tie pouzita v nejakej story - ziskame tym aj navod ako sa to ma/moze pouzit.

**Comment by janmichek** [comment]
Tabs se vyskytuji v kbc ->

https://github.com/keboola/kbc-ui/blob/58d6f91f6e0a89b4c0b9117deebf938168997661/src/scripts/modules/limits/Index.jsx

https://github.com/keboola/kbc-ui/blob/5b00f90dd7f340ee393b84912a4e5d6101b9c931/src/scripts/modules/oauth-v2/react/AuthorizationModal.jsx#L68

https://github.com/keboola/kbc-ui/blob/b3fdb73b80c0f606c9b8428959879a5e4fff1f7e/src/scripts/modules/orchestrations/react/pages/orchestration-job-detail/OrchestrationJobDetail.coffee#L69

https://github.com/keboola/kbc-ui/blob/1e5c1502907614a9e554b4d65c6ff2cb3d3da66b/src/scripts/modules/tokens/react/TokenDetail.jsx#L71

https://github.com/keboola/kbc-ui/blob/5ff5a5753cab3d0d4f98eae2be3a38c63ed0e39a/src/scripts/modules/tokens/react/Index/Index.jsx#L9

https://github.com/keboola/kbc-ui/blob/58d6f91f6e0a89b4c0b9117deebf938168997661/src/scripts/modules/trash/react/pages/TrashIndex.jsx#L15

https://github.com/keboola/kbc-ui/blob/b3fdb73b80c0f606c9b8428959879a5e4fff1f7e/src/scripts/modules/wr-google-sheets/react/components/SheetModal.jsx#L41

https://github.com/keboola/kbc-ui/blob/58d6f91f6e0a89b4c0b9117deebf938168997661/src/scripts/react/layout/SettingsTabs.jsx#L11

https://github.com/keboola/kbc-ui/blob/b3fdb73b80c0f606c9b8428959879a5e4fff1f7e/src/scripts/modules/ex-twitter/react/wizard/WizardCommon.jsx#L16

https://github.com/keboola/kbc-ui/blob/5b00f90dd7f340ee393b84912a4e5d6101b9c931/src/scripts/modules/gooddata-writer/react/pages/table/DateDimensionSelectModal.coffee#L67

**Comment by janmichek** [comment]
PRacuju na tom v tyhle vetvi https://github.com/keboola/indigo-ui/tree/unify-tabs
Ve finale to mozna ani nemusime mergovat to masteru, staci na tom pracovat na lokale.
Pokud by to bylo sjednoceny -> potom staci jednoduchy priklad pouziti. Uvidime co z toho vyleze.

**Comment by janmichek** [comment]
Myslim ze uz jsem prisel na to jak to vycistit a sjednotit

- Přesunout custom styly z kbc do stylu indiga s prefixem (.indigo-tab-pane .tab-pane)
- Pripsat custom classu do Tabs v kbc
- Bacha na boj o specificitu stylu, tady ocekavam nejaky docasny prasarny xD
- Nasadit do produkce kbc (predprivait styly tak aby se necekalo az se vybuildi a slo jen prepnout. To jde, zejo?)
- Potom uz budem moc pracovat jen v ramci Indigo (+ vyhodit inline styly). Bude potreba evidovat zmeny
- Upravit pripadne html a inline stejne i v kbc, predbuildovat styly v indigo aby slo jen prepout
- nasadit do produkce kbc
- odebrat uz nepouzivanou custom classu
- pripravit demo pouziti v indigo

@ujovlado zkus se nad tim kriticky zamyslet jestli muj plan nema nejaky mouchy

**Comment by janmichek** [comment]
Ok, snad je to dobry postup. Ted bych potreboval vybuildovat novy styly pro lokalni verzi KBC.
https://github.com/keboola/indigo-ui/pull/88
Nenasel jsem jak se to dela, zas nechci pushovat a tagovat v masteru, at se to nerozesere v produkci KBC. Pls help @ujovlado

**Comment by janmichek** [comment]
Jak udelam abych pouzil novejsi styly na zkousku na lokale kbc a zaroven se to jeste necpalo do masteru kbc?

**Comment by ujovlado** [comment]
Ten postup, co si pisal tu vyssie, vyzera celkom fajn. Bude to ale musiet fungovat simultanne -> t.j. uz budu releasnute a nasadene styles `.indigo-tab-pane` ale este nebudu nikde pouzite. Nasledne sa to prepne na nove styles (`.indigo-tab-pane`), a az potom sa mozu vymazat tie stare.

Je to trosku komplikovanejsie, ale je to imho jediny sposob ako to spravit bezvypadkovo. ;)

**Comment by ujovlado** [comment]
Ako to vyvijat spolu s kbc-ui ti napisem podrobnejsie do #88

**Comment by janmichek** [comment]
Fajnovy, tak ja na to cekam .]

**Comment by ujovlado** [comment]
Fixed by #102
