### ISSUE TITLE
Output Mapping - selector "kam zapsat"

### ISSUE THREAD

**Issue by jancermak** [keboola/indigo-ui#85]
Dneska je tam jeden field, kde nic není, pokud je projekt novej. Rád bych tam alespoň výběr bucketu a existující tabulky nebo explicitní návod na nový bucket / tabulku.

**Comment by kacurez** [comment]
@jancermak myslis toto?
![image](https://user-images.githubusercontent.com/1412120/34209716-a33fb33e-e593-11e7-8172-ea98811b8f99.png)
- `Source` sa mapuje na to co je vo vystupe napr. sql scriptu a nato zatial nemame funcknu podporu to z toho vyparsovat..
- `Destination` - ked zacnes pisat tak sa ti tam zobrazi zoznam tabuliek, ale suhlasim ze by to malo byt intuitivnejsie, tj hned po kliku zobrazit ponuku po tabulkach a bucketoch ajked su prazdne.

**Comment by jancermak** [comment]
Ano 

P.S: jak jsem to prepnul na issue tak se ten padakuv popisek prepnul na muj commment.

**Comment by jancermak** [comment]
Tady - jsou rozkresleny dve varianty i s mejma popiskama a dotazama https://invis.io/YRF9S44N3#/272754322_KBC_85-_Output_Mapping_-_Selector_Kam_Zapsat

A tady je spojenim verze 1 + 2 vzniklej prototyp 
https://invis.io/YRF9S44N3#/272754321_KBC_85_-_01

Prosim kouknete na to.

Popis, dotazy k tomu vsemu:
1. source — dokazame nazev source tabulky, vytahnout z toho SQL kodu co tam pise uzivatel? (naivne si myslim ze staci v kodu najit CREATE TABLE a zkopirovat co je v uvozovkach za tim) — pokud ano muzeme uzivateli nabidnout source jako select tech tabulek vznikly v transformacni DB. 
Jedine omezeni je to ze output mapping musi delat az po zadani SQL querry. Coz nahrava prehozeni casti transformace tak aby to davalo smysl — 1.input mapping / 2. sql querry / 3. output mapping

2. destination — jsem rozdelil na dve casti — create new table / use existing table
U create new table jsem pochopil ze existuje pravidlo jak psat nazev  a to “out.c-NECO.NECO” — proto jsem v prototypu navrhl skladani cesty z out.c- k tomu pridat nazev bucketu a transformace bucket-transformace a za to dat zvoleny source — tedy 
out.c-nazev_bucketu-nazev_transformace-source

Vyber existujici tabulky — po kliknuti do inputu - bud v nem mohu hledat pomoci zadani jmena, ci se mi otevre naseptavac ve kterem bude vypis storage - to co tam je rychla predstava - zakladni rozdeleni je na in.c- a out.c- podtim jsou sloucene “adresary” a u kazdeho adresare si muzu rozbalit tabulky co jsou v nem.

Dekuju za pripominky, ci rozbiti.

**Comment by ondrejhlavacek** [comment]
Nejdřív OT: `Show more` ❤️ , kurvafix a my všude na tohle používáme checkboxy. 

@janmichek co to použít místo panelu v Credentials tady?

![](http://g.recordit.co/miRsOVPHiF.gif)

**Comment by ondrejhlavacek** [comment]
1) Teoreticky bychom měli bejt schopný to vyparsovat, ale je dost možný, že to ne vždycky bude správně - těch možností zápisu CREATE TABLE/CREATE VIEW může bejt víc a nebudeme schopný asi vše podchytit (navíc se ten parsovací skript může seknout), takže tam musí bejt určitě možnost doplnit i něco, co není v seznamu (s prázdným seznamem můžeme začít a parsovat to až později). 

Přehození queries a output mappingu by bylo super, teď je to v tomhle pořadí proto, že queries můžou mít na výšku asi kilometr, takže bys pro output mapping skroloval někam děsně dolů. Pokud by tam bylo nějaký `Show more` nebo `Expand`/`Collapse` u textarey na queries, tak by se to asi vyřešilo. 

2) To mi taky přijde dobrý. Chvilku jsem tápal nad tím, že když mám novou transformaci, zvolím `Create new table`, tak po jením prvním spuštěním se to vlastně celý přesune do `Use existing table`. Taky si nejsem jistej, jestli chceme/dokážeme forcovat že všechny výstupy z transformace jdou do `out`, můžou bejt scénáře, kdy je potřeba to zapsat do `in` (na to by mohlo bejt přepínátko v `Show details`. Selektor tabulek pro `Use existing table` je super, nedělal ale @kacurez něco podobnýho pro `Source table`? Používalo to metadata, lidsky čitelný názvy, obrázky komponent, kterejch se to týkalo. Mohly by se vyfiltrovat jen buckety, který byly založený ručně nebo transformací (a opět, chceme/můžeme něco takovýho forcovat?). Pokud to chceme udělat jako inkrementální změnu, musí to bejt kompatibilní se stávajícíma transformacema. Nějaký chytřejší věci si můžeme dovolit jen u projektů na zelený louce.

Identifikátory typu `out.c-nazev-transformacniho-bucketu-nazev-transformace.tabulka` chceme začít pro uživatele skrývat, důvodů je několik.

Například když uživatel přejmenuje transformaci nebo transformační bucket, identifikátor tabulky už je zafixovanej. Názvy a identifikátory ve storage potřebujeme od sebe oddělit. Už teď se nový transformační buckety a transformace zakládají s číselnejma identifikátorama, který jim zůstavají trvale a jméno bucketu a transformace jsou pouze metadata. Nový komponenty používají tzv. `default bucket`, tj. jejich data jdou automaticky do bucketu s identifikátorem `in.c-{ID_KOMPONENTY}-{ID_KONFIGURACE}`, tj třeba `in.c-keboola-ex-mysql-12345678`. Ty čísla uživatelům nic neřeknou, ale v metadatech bucketu (a tabulek uvnitř) je uložený z jaký konfigurace to vzniklo a v UI by se uživateli měl zobrazit vždy aktuální název konfigurace. V takovým bucketu jsou pak tabulky pojmenovaný už slovně, nečíselně. 

Jak z tohodle vybruslit úplně nevím, pokud by Kacurezuv krásnej barevenej Source selector už  byl všude, dokážu si představit, že kromě `Create new table`, `Use existing table` by přibyla možnost `Auto`, ve který bys vlastně nezadával vůbec nic. Identifikátor bucketu by se stvořil podle šablony `out.c-transformation-{ID_BUCKETU}-{ID_TRANSFORMACE}`, jako název tabulky by se použil název ze `source` a v `Show details` bys třeba jen přepnul, že to chceš dát do `in` místo do `out`. A nejradši bych z těch 3 variant zase nějakou zmizel a měl tam jen 2 (třeba `Default table`, `Custom table`, ale nevím jak :-).

**Comment by kacurez** [comment]
@ondrejhlavacek Jack o tom selectore tabuliek vie, ukazoval som mu to, pacilo sa mu to a dohodli sme sa ze to este zpracuje a mozno trocha vylepsi/ocisti.

> zvolím Create new table, tak po jením prvním spuštěním se to vlastně celý přesune do Use existing table

^^ good point. Nieco podobneho je momentalne v google drive/sheet writery ze ked editujem tak uz vlastne vyberam z existujucej tabulky, netvrdim ze to je zle ale trocha ma to matie. 

Mne sa paci `auto` mode ako pise Najlos. Zadam nazov source tabulky z sql scriptu a zbytok sa vygeneruje podla default sablony. Vacsia customizacia by sa skryla do `show details`. Treba potom domysliet editaciu, napr ked chcem zmenit source tabulku ale chcem zachovat destination tabulku. 
Dalej sa vystupne tabulky z transformatie pouzivaju najcastejsie pri konfiguracii writerov - tam bude dobre mat ten Table Selector by components/configs kde si vyberiem tabulku podla nazvu transformacie a transformacneho bucketu(nemylit so storage bucketom :)). Zaroven si na tomto mieste nemusim nic viac pamatat k strukture vystupnych tabuliek transformacie, tj ze su ulozene v buckete `out/in.c-xyz`..

**Comment by odinuv** [comment]
Jeste dve drobnosti co me dneska napadly - vytahnout nazev tabulky z create table by mohlo celkem fungovat, ale problem je v tom, ze tech CREATE tam typicky byva vic nez tabulek, ktery chces mapovat (docasny tabulky), takze to imho musi byt jen ve forme naseptavace

pokud se presune OM za script, tak je potreba dohlidnout na to, aby transformace nesla spusit bez OM

**Comment by padak** [comment]
Mojích 5 centů: brutálně nás pálí ten existující selektor, fixněme v kroku #1 tuhle situaci a pak pojďme řešit, jak to má vypadat s podporou metadat. Ať to není jako Try Mode, kterej se vleče měsíce a přitom to měl bejt jednoduchej intro-guy do struktury UI.

NIKOD novej není schopnej použít Output mapping, pokud to nevidí někde nastavené. Je to past. Chtěl jsem jednoduše vylepšit tuhle past a pak se vraťme k tomu, jak to má bejt finálně. Co vy na to?

**Comment by odinuv** [comment]
jakoze prehodit script pred om a predvyplnit `source` v om ?

**Comment by padak** [comment]
ne, pořešit aby když dáš přidat om, neměl jsi holý field kde nevíš co napsat

**Comment by odinuv** [comment]
no o tom mluvim, ale kdyz to mas v poradi im - om - script, tak budes mit vzdy v om holy field, protoze neni kde ho vzit

**Comment by Halama** [comment]
to bysme ti tam ale mohli rict ze nemas zadny skript. Me se to prohozeni poradi moc nezda, i kdyz vim ze si na to poradi ve kterem to je ted par lidi stezovalo...

**Comment by odinuv** [comment]
to bysme mohli, me se to prohozeni poradi sice osobne taky moc nezda, ale nenasel jsem k tomu jinej racionalni duvod nez, ze jsem zvyklej psat if leva zavorka, prava zavorka a pak ten vnitrek, pokud dokazem dohlidnout na to, aby uzivatel udelal ten om (tj. tu pravou zavorku), tak asi fakt neni zadnej duvod pro to mit poradi im-om-script

**Comment by padak** [comment]
@odinuv to ale nevadí. je to "jinej" ux pat. Jakmile zapneme validaci SQL od Sqldepu, tak když budeš mít OM a nebudeš mít SQL, tak ti povíme, že děláš mapping co na něj nemáš SQL.

**Comment by Halama** [comment]
no to je to co jsem psal, a muzeme to parsnout klidne lokalne

**Comment by padak** [comment]
jj, mě ale neděsí to že to je prázdný (chápu že to poznáme snadno), ale to že to nenastavíš :) A to že to je prázdný, se sveze s komplexní analýzou "překlepů" co Najloš brzo nasadí

**Comment by odinuv** [comment]
no ja chtel jenom rict, ze tim, ze kdyz to das do poradi im->script->om, tak bude najednou 3/4 lidi jasny, co se po nich chce a kdyz se to jeste predvyplni om necim ze script, tak problem solved?

**Comment by padak** [comment]
jj, souhlas, ale to pořád bude blbý UI, my chceme řešit pořadí, fáze dát pryč, nemíchat backendy, atd... tohle je nakreslený. pojďme to stávající nevylepšovat, jen fixnout roadblock a pak dotáhnout to nakreslený UIčko

**Comment by jancermak** [comment]
@padak @kacurez @odinuv @ondrejhlavacek @Halama @janmichek 

**Posilam navrh hotfix verze.**

https://invis.io/YRF9S44N3#/273960889_KBC_85-_Output_Mapping_-_Selector_Kam_Zapsat_Ver4

**Comment by janmichek** [comment]
super-fajn, rozhodne posun. 
Jediny u ceho jsem se seknul je ze jsem chvili hledar rozdil mezi 5A a 5B.
TO ovladani je dost minimalisticky, ale nerikam ze to vadi.

**Comment by padak** [comment]
@jancermak za mě super! Jak input mapping, tak output mapping.

**Comment by odinuv** [comment]
pujde to pouzit i na tohle https://github.com/keboola/kbc-ui/issues/873 ?

**Comment by padak** [comment]
@jancermak týpek reportuje že v output mappingu může začít jméno tabulky podtržítkem, ale pak to crashne. Bylo by super to fixnout v UI, aby to nemohl zadat (viz https://keboola.productboard.com/inbox/notes/1156429) #fyi

**Comment by janmichek** [comment]
@ondrejhlavacek muzes nas prosim updatnout v jakym je to stavu? Uz jsem nedohledat u issue. Zitra tady bude Jack, tak at to muzem projit. Kuju!

**Comment by ondrejhlavacek** [comment]
@janmichek na tomhle jsem imho nic nedělal?

**Comment by jancermak** [comment]
@padak — zalozil jsem na to issue tady — https://github.com/keboola/indigo-ui/issues/134
