### ISSUE TITLE
Input mapping - výběr časů

### ISSUE THREAD

**Issue by jancermak** [keboola/indigo-ui#89]
Potřebujeme umožnit zvolit víc než přednastavený časy. Viz https://keboola.productboard.com/inbox/features/265607

**Comment by jancermak** [comment]
@padak 

Krome toho casu jsem upravil i vzhled input mapingu, aby byl podobny output mappingu co jsem ted delatl.

Navrh zde — https://invis.io/M6FDR3VGDBP#/273994086_89_-_Input_Mapping

**Comment by padak** [comment]
Za mě super!

Dne st 17. 1. 2018 17:29 uživatel Jan Cermak <notifications@github.com>
napsal:

**Comment by ondrejhlavacek** [comment]
Čau,

nezdá se mi možnost zadat `1 day 10 hours 30 minutes 50 seconds`. Nedává to IMHO smysl, pravidelný procesy pouštíme v dost jednouše definovanejch intervalech, takže pokud ti proces běží každej den, nepotřebuješ mít dosah dozadu `1 day 10 hours`, ale zjednodušeně stačí 2 days. Zároveň kombinovat víc od sebe vzdálenejch řádů nedáv smysl (dny a minuty, hodiny a vteřiny). V extrému bych klidně i řekl, že kdybys opravdu potřeboval `1 day 10 hours`, tak to zapíšeš jako `34 hours`. 

Jako custom period bych teda asi viděl něco jako `[ Počet ] [ Jednotka ]`, kde jednotka je `Days/Hours/Minutes/Seconds` a počet bude čistej číselnej input. 

Druhá možnost mě napadlo do toho inputu nechat uživatele napsat libovolnej text (kromě již předvyplněných hodnot).

![image](https://user-images.githubusercontent.com/497675/35150235-ecdad8be-fd19-11e7-9912-ebfa9fd7182e.png)

Místo `No results found` by tam bylo `Add 34 hours` nebo něco podobného.

**Comment by jancermak** [comment]
@ondrejhlavacek @padak @janmichek 
Ahoj nahodil jsem prototyp se 3 verzema moznosti delani custom periody.

https://invis.io/B4GOLGEVNWQ#/289223468_89_-_Home
