### ISSUE TITLE
Publish styleguide

### ISSUE THREAD

**Issue by ujovlado** [keboola/indigo-ui#9]
Nemalo by to byt zlozite, storybook ma myslim command na zbuildovanie.

Staci sa dohodnut na domene a niekto to moze pripravit.

Ten build by mal byt cez travis (idealne asi po pushnuti tagu).

Kroky pre build:
- nejaky `storybook build`
- deploy `build` (alebo kde to da) priecinku do s3 (to uz mame kadetade, napr. na developers-docs alebo kbc-ui)

Aby to bolo na domene pod https bude treba:
- nastavit route53 smerujuci na cloudfront distribuciu
- nastavit cloudfront smerujuci na spominanu s3
- nastavit redirect http -> https

To by malo byt vsetko, da sa to zbuchnut rychlo.

**Comment by janmichek** [comment]
Okacko, na strane aplikace jsem pridal ty build scripty.
https://github.com/keboola/indigo-ui/commit/43b6c80294c26fc5b22f0eacfe98acc3d42a09ce
jsem pro domenu "indigo.keboola.com"

Predpokladam ze je ted potreba zalogovat se do S3 adminu, tam to nejak nakonfigurovat, ziskat heslo a vlozit ho do travis souboru. Tak nejak podobne na cloudfront.
Marne hledam v nasem 1passwordu logovaci udaje. 
Jak to mam udelat?

**Comment by ujovlado** [comment]
tie udaje do bucketu v s3 ti nastavim to travisu, nech sa s tym nemusis babrat (cloudfront a route53 spravime neskor)

**Comment by janmichek** [comment]
Dikyn, yarn.lock updatnut

**Comment by ujovlado** [comment]
@janmichek 
s3 bucket: `indigo-ui-site-services-indigouis3-5izu6yd9zfix`
region (ak treba): `us-east-1`
aws access key a secret je v travise: https://travis-ci.org/keboola/indigo-ui/settings

**Comment by ujovlado** [comment]
^ aws access key a secret potom treba pouzit ako environment premenne

**Comment by ujovlado** [comment]
zatvaram, na to https som spravil issue ( #11)
