### ISSUE TITLE
inline inputy ve form horizontal 

### ISSUE THREAD

**Issue by janmichek** [keboola/indigo-ui#99]
udelat funkcni predlohu ala

https://user-images.githubusercontent.com/1412120/36238264-7f0a8a22-123c-11e8-8e9a-64dabba417ac.png

https://react-bootstrap.github.io/components/forms/#forms-layout

**Comment by ondrejhlavacek** [comment]
Vím, že úplně OT v tuhle chvíli, ale minulej tejden jsem u Jacka viděl úplně skvělý řešení na to `Show more`, ty checkboxy jsou strašný :-) Mám to někde vyhrabat a zaevidovat?

**Comment by janmichek** [comment]
@ondrejhlavacek  ano prosim, nahod issue dix

**Comment by ondrejhlavacek** [comment]
https://github.com/keboola/kbc-ui/issues/1485

**Comment by ujovlado** [comment]
V kbc-ui sme to s @kacurez zatial vyriesili flexboxom. T.j. mozno by stacilo spravit nejaku wrapper komponentu, ktory by mala `display: flex` a vsetkym svojim children `form-control` by nastavila `flex: 1`.

Alebo ako to mas v plane? :)

**Comment by janmichek** [comment]
Jo, s flexboxem jsem v pohode.
Ty tecky 'kbc-dot-separator' bych zkusil vyresit pomoci :after selectoru.
Nevim, potreboval bych se do toho zavrtat a zjistit jestli je to mozny, zatim spekuluju.
V tech formech me drazdi hlavne <div class="row col-md-12">
